Builder/ListBuilder.php
Builder/ShowBuilder.php

Same method as #235 but for list templates.
Also remove trailing whitespaces on `showBuilder` class.
Could you push a new 2.3 stable version after this merge?
Thanks.

Don't overwrite list templates defined in config

---

Resources/views/Form/form_admin_fields.html.twig

Move the ``field-short-description`` element outside from the ``.fields-actions`` element, to allow more precise styling on the action buttons.
JS is still working.

Update sonata_type_model_list template

---

DependencyInjection/SonataDoctrineORMAdminExtension.php
Resources/config/doctrine_orm.xml
Tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php

This PR replace `factory-service` and `factory-method` attributes by `factory` section, according to Symfony deprecate rules.
`factory` section was introduce on Symfony 2.6 (https://github.com/symfony/symfony/pull/9839) so this PR will break support of `symfony/dependency-injection` minor to 2.6.
If you are OK with not supporting symfony < 2.6 anymore, just merge this PR.
Otherwise, I will update it to look like this kind of PR: https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1765/files
Regards

Fix deprecated factory definition

---

Datagrid/ProxyQuery.php
Tests/Filter/QueryBuilder.php

| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | sonata-project/SonataAdminBundle#2884
If developer overload `createQuery` method in admin class, we should not `leftJoin` entities that are already joined. Too many same `leftJoin`s breaks the query performance and may cause unexpected results.

Do not add left join to already joined entities with custom query

---

Datagrid/ProxyQuery.php

Actually, the ProxyQuery can't handle identifier with relational link properly. This PR patch this.
It's a corrected version of #226 and concern issus #225, https://github.com/sonata-project/SonataAdminBundle/issues/1392 and https://github.com/sonata-project/SonataAdminBundle/issues/1000 as far I know.
I think it's quite critical, please have a look! :+1: 
Thanks.
I give you some steps to reproduce the error with the current master version.
If we have an entity with relational identifiers like this:
```php
/**
* UserBrowser
*
* @ORM\Table(name="user_browser")
* @ORM\Entity
*/
class UserBrowser
{
/**
* @var User
*
* @ORM\Id
* @ORM\ManyToOne(targetEntity="Nexy\UserBundle\Entity\User", inversedBy="browsers")
* @ORM\JoinColumn(name="user_id", referencedColumnName="id")
*/
private $user;
/**
* …
```

Fix ProxyQuery error on relational identifiers

---

Builder/ListBuilder.php

Q   |   A
------|-------
Bug fix? |	no
New feature? |	no
BC breaks? |	no
Deprecations? |	no
Tests pass? | yes
Fixed tickets | no
License | no
Doc PR | no
Test Purposes: http://www.advanced-javascript.com/2012/11/php-switch-vs-inarray-vs-isset.html
For the Switch took: 2.094s. (3.726s)
For the In_Array took: 1.617s. (2.414s)
For the IsSet took: 0.848s. (0.899s.)

Small Change for Performance

---

Filter/ChoiceFilter.php
Tests/Filter/ChoiceFilterTest.php

This (finally) fix https://github.com/sonata-project/SonataAdminBundle/issues/1061.
Also add an extra `@param` line on PHPDoc block to make it more IDE friendly.

Fix doctrine_orm_choice crash on negative value

---

Filter/CallbackFilter.php
Tests/Filter/CallbackFilterTest.php

Hello,
I tried to use the `field` and `alias` param from the CallbackFilter callback, but I had some issues.
- The `field` param was always empty.
- The `alias` param was incorrect.
Example for incorrect `alias` param :
```php
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
{
$datagridMapper
->add('contact.last_name', 'doctrine_orm_callback', array('callback' => array('MyClass', 'myStaticMethod')))
;
}
``` 
After some research, I found this issue: #472 (for the `field` param)
And here is the pull request to fix it :)
Thank you for your time,
Vincent

Fix CallbackFilter alias and field variables

---

Resources/views/CRUD/edit_orm_one_to_many.html.twig

Updates the design of the one2many tab view in the edit/create form.
Before
After

Updated edit one to many tab design

---

Model/ModelManager.php
Tests/Fixtures/Entity/AssociatedEntity.php
Tests/Fixtures/Entity/ContainerEntity.php
Tests/Fixtures/Entity/Embeddable/EmbeddedEntity.php
Tests/Model/ModelManagerTest.php

I tried to use an embeddable property with dot notation as a form item. Since dot notation items are all treated as associations (no check for embeddables) there was an "undefined index" exception.
~~After adding this patch my form items got rendered correctly~~ the form type guessers don't receive/deduce the correct field information / form widgets. The form just falls back to text-input defaults.
N.B.: uninitialized embedded objects (`null`) will also break somewhere at the `PropertyAccessor` level.

Embedded class support

---

Datagrid/Pager.php

Removed unused property

---

Resources/views/CRUD/edit_orm_many_to_many.html.twig

On default behavior (inline, not table), the `action_delete` translation was not included.
Tested on local machine, everything seems working fine.

[Translation] Add delete checkbox translation in collection

---

Datagrid/ProxyQuery.php
Tests/Datagrid/ProxyQueryTest.php

When declaring a field from an embedded entity as a table identifier
the ProxyQuery will use the fieldName as a parameter placeholder. This
triggers a semantical error in the query builder.

Embedded identifier support

---

composer.json

Fixes #509 .
ACLs have been moved out of Symfony since version 2.8. See
https://github.com/symfony/symfony/issues/14718

fix broken build

---

Datagrid/ProxyQuery.php

I needed to extend ProxyQuery in order to add query hints in the execute() method.
Does it make sense to make the getFixedQueryBuilder method protected instead of private ?

change ProxyQuery::getFixedQueryBuilder to protected

---

Resources/views/CRUD/edit_orm_one_to_many.html.twig

When using `sonata_type_collection` with inline/table, custom `translation_domain` is ignored :
```php
->add('commission', 'percent', ['translation_domain' => 'CustomDomain'])
```
**Before**
**After**

Use translation_domain on collection labels

---

Tests/Filter/FilterTest.php

A unit test should not test methods defined outside the class under
test, even if it is a parent class, and especially if this class is
defined in another package.

do not test dependencies

---

Resources/doc/reference/form_field_definition.rst
Resources/views/CRUD/edit_orm_one_to_many.html.twig

A 'limit' option can be passed to 'sonata_type_collection' form fields to limit the number of fields that can be added. This works by removing the "add" button after that amount of elements have been added. No actual enforcing is done when persisting entities.
Docs have been updated

Added limit to the number of elements added with sonata_type_collection

---

composer.json

Since you made change on the core bundle this week end, there is a conflict between the blockbundle and the doctrine orm bundle.
They should require the 3.x-dev branch and not the 2.x anymore.
Fixes #537

Fixing dependencies problem since 3.x-dev update

---

composer.json

The added knplabs/knp-menu-bundle requirement have to removed when issue linked below will be resolved.
https://github.com/composer/composer/issues/5355

Fix lowest dependencies issue with knp-menu-bundle

---

CHANGELOG.md
Datagrid/ProxyQuery.php
Model/ModelManager.php
Resources/doc/reference/list_field_definition.rst
Tests/Datagrid/ProxyQueryTest.php
Tests/Fixtures/DoctrineType/UuidType.php
Tests/Fixtures/Entity/UuidEntity.php
Tests/Fixtures/Util/NonIntegerIdentifierTestClass.php
Tests/Model/ModelManagerTest.php

_Resubmitted PR #523 to the correct branch after switching release strategy_
Description from #523:
> 
> I came across this issue/case when using an entity with uuid identifier and prefilled (uuid generated in the entity) identifier
> 
> Example:
> ```php
> use Ramsey\Uuid\Uuid;
> 
> class Example
> {
>     /**
>      * @var \Ramsey\Uuid\Uuid
>      *
>      * @ORM\Column(type="uuid")
>      * @ORM\Id
>      */
>     private $id;
> 
>     public function __construct()
>     {
>         $this->id = Uuid::uuid4();
>     }
> }
> ```
> 
> Problems:
> - Create page could not be opened (as the identifier class could not be resolved)
> - prefilled identifier caused the code to think it was editing an existing item
> 
> Fixes:
> - Use the database value of each type to display the entity
> - …

Get database value of identifier to support other identifier type classes

---

Datagrid/ProxyQuery.php
Tests/Datagrid/ProxyQueryTest.php
composer.json

Closes #565
Replaces #566
```markdown
- Avoid duplicate field in ORDER clause
```
Fix issue #565 "A column has been specified more than once in the order by list"

Post hawk 565 fix

---

Admin/FieldDescription.php
Resources/doc/reference/list_field_definition.rst
Resources/doc/tutorial/creating_your_first_admin_class/defining_admin_class.rst
Resources/doc/tutorial/creating_your_first_admin_class/defining_entities.rst
Tests/Admin/FieldDescriptionTest.php

```markdown
- Support embedded object for mapping
```
This PR allow to use embedded object in the show mapper. 
```php
class Foo {
public function getValue()
{
return 'myValue';
}
}
class Bar {
public function getFoo()
{
return $this->foo;
}
}
```
``` php
protected function configureShowFields(ShowMapper $showMapper)
{
$showMapper
->add('foo.value');
}
```
The FieldDescription method getValue ignore the embedded object and do 
``` php
$bar = new Bar();
$bar->getValue()
```
With my PR the getter call is on the embedded object and not on the parent object.
``` php
$bar->getFoo()->getValue()
```

Support embedded object for mapping

---

Datagrid/ProxyQuery.php
Model/ModelManager.php
Tests/Datagrid/ProxyQueryTest.php
Tests/Fixtures/Entity/AssociatedEntity.php
Tests/Fixtures/Entity/ContainerEntity.php
Tests/Model/ModelManagerTest.php

Closes #585
```markdown
- Failing identifier management for relations as id
```
PR #547 brought other identifier types support.
This uses `Type::getType` method with `ClassMetada::getTypeOfField` returned value.
`ClassMetada::getTypeOfField` can return null and then `Type::getType` throw an exception.
This can be reproduced with an entity having a relation as an identifier.
Plus, the given type field may be not mapper under Type map.
Checking `ClassMetada::getTypeOfField` return value and use `Type::hasType` before solve the issue.

Ensure DoctrineType is available before using it

---

Builder/DatagridBuilder.php
Builder/FormContractor.php
Tests/Builder/DatagridBuilderTest.php
Tests/Builder/FormContractorTest.php
composer.json

Replaces #587 
```markdown
- Deprecated usage of `form` type name
```

Replace deprecated 'form' type by FormType class

---

Builder/FormContractor.php

```markdown
- Fix wrong property name on FormContractor
```
The other is never used. As a protected one, I keep it for BC.
Because of the deprecation, this should be delivered as a new minor.

Fix wrong property name on FormContractor

---

Resources/views/CRUD/edit_orm_many_association_script.html.twig

```markdown
- Create form is shown instead of filters on `sonata_type_model_list` popup 
```
When using `sonata_type_model_list`, dropdown filters are not working inside the list popup due to an AJAX call. This function is catching that website click, so we must assure that the click href contains something different than *empty* and *#* to make the AJAX request. `return` is needed so other JS files are able to catch that event. For example: Bootstrap dropdown (filters, as seen in previous lines).

Fix not working filters on model list popup

---

Builder/FormContractor.php
Tests/Builder/FormContractorTest.php

I am targetting this branch, because it is a bug fix.
- fixed: allow not mapped field to use `admin_code` option for `sonata_type_model_list`
When you have field with option `mapped => false`, example:
```php
->add('company', 'sonata_type_model_list', [
'btn_add' => false,
'btn_delete' => false,
'mapped' => false,
'class' => Company::class,
], [
'admin_code' => 'sonata.admin.company',
])
```
This error occurs:
```
Impossible to invoke a method ("id") on a null variable in SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig at line 59
```
This patch fixes error and allow not mapped filed work with `sonata_type_model_list`.

Allow not mapped field to use `admin_code` option

---

Filter/AbstractDateFilter.php
Resources/doc/reference/filter_field_definition.rst
Tests/Filter/DateRangeFilterTest.php

Fixes #408
```markdown
- Date range filter can now be used with only one side defined
```
It is now possible to only set one date for a range. With this it will filter to all records until or from the given date.

Ability to use the date range filter with an open end on either side

---

Resources/views/CRUD/edit_orm_one_to_many.html.twig

I am targetting this branch, because…
```markdown
- Adds missing translation of 'Delete' in edit view
```
The `Delete` label wasn't translated.

Adds missing translation of 'Delete' in edit view

---

Builder/FormContractor.php

I am targetting this branch, because…
```markdown
- `FormContractor` supports the new `Sonata\AdminBundle\Form\Type\ModelListType`
```
This is a fix, to support the new `ModelListType` type too.
Refs https://github.com/sonata-project/SonataAdminBundle/pull/3978

Fixed FormContractor for new ModelListType

---

Filter/AbstractDateFilter.php
Filter/BooleanFilter.php
Filter/CallbackFilter.php
Filter/ChoiceFilter.php
Filter/ClassFilter.php
Filter/ModelAutocompleteFilter.php
Filter/ModelFilter.php
Filter/NumberFilter.php
Filter/StringFilter.php

I am targetting this branch, because…
```markdown
- Use class names for filters when using symfony 2.8+
```
This will reduce some deprecation warnings and supports the new class usage for forms.

Improved support for symfony3

---

Tests/Admin/FieldDescriptionTest.php

I am targetting this branch, because this is a patch
This is a workaround for a phpunit mock objects bug, see https://github.com/sebastianbergmann/phpunit-mock-objects/pull/324
To be merged ASAP :rotating_light:

Mock class that exists

---

Resources/views/CRUD/edit_orm_one_to_many.html.twig

I am targetting this branch, because this change is a small bugfix (hotfix).
```markdown
Two wrong twig file paths
```
In the last PR merge happened a mistake where two file paths were entered wrong.

fixed twig includes

---

Builder/DatagridBuilder.php
Filter/BooleanFilter.php
Filter/CallbackFilter.php
Filter/ChoiceFilter.php
Filter/ClassFilter.php
Filter/DateFilter.php
Filter/DateRangeFilter.php
Filter/DateTimeFilter.php
Filter/DateTimeRangeFilter.php
Filter/ModelAutocompleteFilter.php
Filter/ModelFilter.php
Filter/TimeFilter.php
Guesser/FilterTypeGuesser.php

I am targetting this branch, because it's about avoiding deprecation warnings when using Sf >= 2.8, while keeping the old behavior.
```markdown
- Use class name when referencing `Form Type` to be compatible with Symfony 2.8+
```
Closes #613
Remove deprecation warnings when using Sf >= 2.8

Replaced form type names with classnames

---

Builder/FormContractor.php
Tests/Builder/FormContractorTest.php

I am targetting this branch, because there are no BC breaks.
```markdown
- Changed how `FormContractor::getDefaultOptions` checks which type is used. Instead of checking for an array of available types, we improve this by checking for the class instance or parents. 
```
This fixes an issue, when you for example try to extend ModelAutocompleteType, you will receive a fatal error: `Catchable Fatal Error: Argument 1 passed to Sonata\AdminBundle\Form\DataTransformer\ModelToIdPropertyTransformer::__construct() must implement interface Sonata\AdminBundle\Model\ModelManagerInterface, null given, called in /app/vendor/sonata-project/admin-bundle/Form/Type/ModelAutocompleteType.php on line 37 and defined.`
That was because it only checks for the ModelAutocompleteType, and not types extending it.

Fix formcontractor typecheck for classes

---

Resources/views/CRUD/edit_orm_one_to_many_sortable_script_table.html.twig

I am targeting 3.x, because this is a bug fix, to match expected behaviour.
```markdown
- Nested sortable table form items not persisted on save
```
With nested sortable forms, the child form's position elements are not updated.
The 'sortable' jQuery plugin finds _all_ child `tdbody.sonata-ba-tbody` elements, _including_ those _in child forms_, and only triggers the _parent form_'s handler.
This means when you re-order child elements, the parent form's hidden position fields are updated even though they haven't changed, and the child form's position fields are not updated.
By restricting to the first (outer most) match, the `.sortable(` attempting to bind to the child form is able to react to its own events.

Nested sortable table form items not persisted on save

---

Model/ModelManager.php

I am targetting this branch, because…
the changes in this PR make the existing code more robust and address possible bugs caused by the UnitOfWork not carrying already-persisted entities in some scenarios
See discussion:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/547#r80505888
```markdown
- Changed how persisted entities are detected, now using `UnitOfWork::getEntityState()` instead of `isInIdentityMap()`
```
Instead of looking at the UnitOfWork identity map (which may detach objects after a flush), this revision uses the reported entity state which should be a more robust indicator of whether or not a given entity has been persisted

Improve detection of entity persistence:

---

Filter/ModelFilter.php
Model/ModelManager.php

I am targetting this branch, because this is a bugfix.
```markdown
- Typo on `RuntimeException` usages
```

Fix typo on RuntimeException usage

---

Resources/views/CRUD/list_orm_many_to_many.html.twig
Resources/views/CRUD/list_orm_many_to_one.html.twig
Resources/views/CRUD/list_orm_one_to_many.html.twig
Resources/views/CRUD/list_orm_one_to_one.html.twig
Resources/views/CRUD/show_orm_many_to_many.html.twig
Resources/views/CRUD/show_orm_many_to_one.html.twig
Resources/views/CRUD/show_orm_one_to_many.html.twig
Resources/views/CRUD/show_orm_one_to_one.html.twig

I am targetting this branch, because it is a bugfix.
Fixes #529
```markdown
- ORM any-to-any list and show templates now use `hasAccess`
```
The ORM ANY-to-ANY list and show templates use uppercased version of route name as role, this causes problem in some routes (eg.: `show` route -> `VIEW` role, `history` route -> `EDIT` role). With the update they use the new `hasAccess` function from `AbstractAdmin` introduced in sonata-project/SonataAdminBundle#3749 to check the role.

Updated orm relations twig files to use hasAccess

---

Builder/FormContractor.php

I am targetting this branch, because this is bug fix.
Related to #327
```markdown
Fixed typo in exception message in Builder/FormContractor.php 
```
Type `sonata_model_list` doesn't exist. `sonata_type_model_list` doesn't work for one-to-many relation, so the suggested form type should be `sonata_type_collection`.

Fix typo in exception message

---

Block/AuditBlockService.php

sonata-project/block-bundle, on 3.x branch, BaseBlockService @deprecated since 3.2, to be removed with 4.0
Fixed deprecated `BaseBlockService` usage, in the 3.x branch of sonata-project/block-bundle

Fixed deprecated BaseBlockService usage

---

Block/AuditBlockService.php

I am targetting this branch, because this was BC in the first place.
Refs #641 
```markdown
- deprecated usage of Sonata\BlockBundle\Block\BaseBlockService
```
This is a backport from a PR that should have been merged in 3.x instead of master.

Fixed deprecated BaseBlockService usage (#641)

---

Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig

I am targetting this branch, because this is BC.
Partially closes sonata-project/SonataAdminBundle#4229
```markdown
- translation in twig templates uses the twig translation filter
Removes deprecated translations calls from the `AdminInterface::trans` method.

Remove deprecated translation logic

---

Builder/DatagridBuilder.php
Builder/FormContractor.php
Filter/AbstractDateFilter.php
Filter/BooleanFilter.php
Filter/CallbackFilter.php
Filter/ChoiceFilter.php
Filter/ClassFilter.php
Filter/DateFilter.php
Filter/DateRangeFilter.php
Filter/DateTimeFilter.php
Filter/DateTimeRangeFilter.php
Filter/ModelAutocompleteFilter.php
Filter/ModelFilter.php
Filter/NumberFilter.php
Filter/StringFilter.php
Filter/TimeFilter.php
Guesser/FilterTypeGuesser.php
Tests/Builder/FormContractorTest.php
composer.json

I am targetting this branch, because bumping versions of php / sf is considered major.
```markdown
- Support for PHP 5.3 through 5.5 was dropped
- Support for Symfony 2.2 through 2.7 was dropped
```
This prepares the next major release

Drop old versions

---

Filter/StringFilter.php
Tests/Filter/QueryBuilder.php
Tests/Filter/StringFilterTest.php

I am targeting this branch because it's a bugfix.
```markdown
- Consider NULL values when using 'does not contain' advanced string filter
```
TYPE_NOT_CONTAINS advanced filter should consider also the NULL values. Instead of
$alias.$field NOT LIKE :$parameterName
you should have
$alias.$field NOT LIKE :$parameterName OR $alias.$field IS NULL
If you have the following values for a field 
['Susoo', NULL, 'Bibee']
If you filter by << does not contain 'Susoo' >>, it should return [NULL, 'Bibee'], not only ['Bibee'] as it is implemented right now.

TYPE_NOT_CONTAINS doesn't consider NULL values

---

Filter/ModelFilter.php
Tests/Filter/ModelFilterTest.php
Tests/Filter/QueryBuilder.php

I am targeting this branch because it's a bugfix.
```markdown
- Consider NULL values when using 'is not equal' advanced model filter
```
TYPE_IS_NOT_EQUAL advanced filter should consider also the NULL values. Instead of
$alias NOT LIKE != :$parameterName
you should have
$alias NOT LIKE != :$parameterName OR $alias.$field IS NULL
If you have the following values for an entity filter 
[3, NULL, 5]
If you filter by << does not contain '3' >>, it should return [NULL, '5'], not only ['5'] as it is implemented right now.

TYPE_IS_NOT_EQUAL doesn't consider NULL values

---

Filter/ModelFilter.php

I am targetting this branch, because it's a bugfix.
Closes #652
```markdown
- Use the right array conversion for filter value
```
The filter value object was converted to array by mistake, now it's just added as the first and unique item of an array, in order to be well processed by the handleMultiple() method.

Use the right array conversion for filter value

---

Resources/views/CRUD/list_orm_many_to_one.html.twig

I am targetting this branch, because this is a bug fix.
```markdown
- Fixed wrong link generation when calling `DatagridMapper::addIdentifier` on mapped field
```
When calling `DatagridMapper::addIdentifier` on a mapped field, the link is generated to the fields admin edit page instead of the current admin edit page.

Fixed wrong entity link in list view

---

Resources/views/CRUD/edit_orm_one_to_many_inline_tabs.html.twig

I am targetting this branch, because this is BC.
```markdown
- Fixed duplicate translation of "Delete" in edit tab view
```
The translation is already handled in the form component, no need for a manual translation using twig function.

Fixed duplicate translation of "Delete" in edit tab view

---

composer.json

I am targetting this branch, because this is BC.
Refs https://github.com/sonata-project/dev-kit/issues/216
This is pedantic because it's only about a development dependency.

Allow simplethings/entity-audit-bundle ^1.0

---

Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig

I am targetting this branch, because this a bugfix.
Closes #656
```markdown
- Fixed broken translation in oneToMany table view
```
The PR #651 breaks the translation of oneToMany form fields in the table view.

Translation is broken in oneToMany edit form

---

Resources/views/CRUD/list_orm_many_to_many.html.twig
Resources/views/CRUD/list_orm_one_to_many.html.twig
Resources/views/CRUD/list_orm_one_to_one.html.twig
Resources/views/CRUD/show_orm_many_to_many.html.twig
Resources/views/CRUD/show_orm_many_to_one.html.twig
Resources/views/CRUD/show_orm_one_to_many.html.twig
Resources/views/CRUD/show_orm_one_to_one.html.twig

Should be check access to the element, not for whole collection.
I am targetting this branch, because this a bugfix.
```markdown
- Fixed view - check specific item collection, not to the whole collection.
```
The error occurs in the view that displays the individual elements of the relationship many-to-many.

Fix check access to object in view

---

Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig

I am targetting this branch, because this is a patch.
```markdown
- Fixed wrong translation in delete checkbox in `edit_orm_one_to_many_inline_table.html.twig`
```
When adding a collection field to the admin form with a sortable position, the `Delete` button will be translated by mistake. The label isn't visible at all in this view.

Fixed wrong translation in one_to_many template

---

Resources/doc/reference/form_field_definition.rst

I am targetting this branch, to enhance documentation.
Closes https://github.com/sonata-project/SonataAdminBundle/issues/4236
```markdown
- Simplify and complete documentation for one-to-many relation

update one to many documentation

---

Builder/ListBuilder.php
Tests/Builder/ListBuilderTest.php

I am targeting this branch, because it's a patch.
Closes #672
```markdown
- A list field with `actions` type will get all the required field options just like the `_action` field.
- `_action` field will get a proper `actions` type.
```
`ListBuilder` fix.

fixes #672 build actions field description based on provided type too

---

Resources/views/CRUD/edit_orm_many_association_script.html.twig

I am targeting this branch, because this is a patch.
Closes #684.
```markdown
- One-to-many and many-to-many association script will not try to load links with "javascript:" hrefs via XHR.
```
One-to-many and many-to-many association script will not try to load links with "javascript:" hrefs via XHR.
Not sure if any other place needs to be changed too, seems to work fine.

Make the association script skip javascript links for loading via XHR

---

Filter/ModelFilter.php

I am targeting this branch, because it does not introduce BC.
```markdown
- `ModelFilter::handleMultiple` fix method to retrieve parent alias for building IDENTITY query part
```
When trying to use this filter with sub relation field and selecting NOT_EQUAL type filtering it throw an error because it uses root alias instead of parent alias.
**Exemple :** 
relations :
myEntity -> Registration -> Diploma
`$datagridMapper->add('registration.diploma')`
The generated dql will try to test IS NULL on o.diploma instead of s_registration.diploma as expected.

ModelFilter fix when not_equal filtering for association depth >= 2

---

composer.json

I am targeting this branch, because currently there is an issue when trying to use `simplethings/entity-audit-bundle:^2.0@dev`.
```markdown
- Fixed `AddAuditEntityCompilerPass::process()` when definition `simplethings.entityaudit.audited_entities` is not present, as of `2.x` version for `simplethings/entity-audit-bundle`.
```
Closes #688.

Add `simplethings/entity-audit-bundle:>=2.0` to `conflict` section at `composer.json`

---

Filter/ModelFilter.php

I am targeting this branch, because this is a bug fix.
```markdown
Fixed wrong DQL generated for many to many relationship when filtering with not equals
```
Currently when using the `ModelFilter` for a many to many relationship and choosing the not equals from advanced filters, will trigger an Exception.
```
[Semantical Error] line 0, col 134 near 'xxx) IS NUL': Error: Invalid PathExpression. Must be a SingleValuedAssociationField.
```

Prevent null check when relationship is many to many

---

Model/ModelManager.php
Tests/Model/ModelManagerTest.php

Closes https://github.com/sonata-project/SonataAdminBundle/issues/4333
```markdown
- Fixed `ModelManager::getDataSourceIterator` when` getSortBy` is empty
```
If you try use export functionality without ordering and disabled sort primary key you got exception.
```php
<?php
namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
/**
* Post
*
* @ORM\Table(name="post")
* @ORM\Entity(repositoryClass="AppBundle\Repository\PostRepository")
*/
class Post
{
/**
* @var int
*
* @ORM\Column(name="id", type="integer")
* @ORM\Id
* @ORM\GeneratedValue(strategy="AUTO")
*/
private $id;
/**
* @var string
*
* @ORM\Column(name="name", type="string", length=255)
*/
private $name;
/**
* Get id
*
* @return int
*/
public function getId()
{
return $this->id;
}
/**
* Set name
*
* @param string $name
*
* …
```

Fixed exception on missing field order by 

---

Filter/ClassFilter.php

Closes [#691](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/691
)
```markdown
Fixed ClassFilter for Symfony 3+. Remove deprecated for Symfony > 2.7

Fixed of not exist ChoiceList  in Symfony 3+

---

Guesser/FilterTypeGuesser.php
Model/MissingPropertyMetadataException.php
Tests/Guesser/FilterTypeGuesserTest.php

Closes #599
Closes #695 
```markdown
- Added `MissingPropertyMetadataException` if property name is not found in field mappings
```
throw `MissingPropertyMetadataException` if propertyName could not be found in mappings
This is based on: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/599/files#r69381571

throw MissingPropertyMetadataException if propertyName could not be found in mappings

---

Tests/Admin/FieldDescriptionTest.php
Tests/Builder/DatagridBuilderTest.php
Tests/Builder/FormContractorTest.php
Tests/Datagrid/ProxyQueryTest.php
Tests/DependencyInjection/Compiler/AddAuditEntityCompilerPassTest.php
Tests/DependencyInjection/Compiler/AddTemplatesCompilerPassTest.php
Tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php
Tests/Filter/BooleanFilterTest.php
Tests/Filter/CallbackFilterTest.php
Tests/Filter/ChoiceFilterTest.php
Tests/Filter/ClassFilterTest.php
Tests/Filter/DateRangeFilterTest.php
Tests/Filter/FilterTest.php
Tests/Filter/ModelFilterTest.php
Tests/Filter/NumberFilterTest.php
Tests/Filter/StringFilterTest.php
Tests/Helpers/PHPUnit_Framework_TestCase.php
Tests/Model/ModelManagerTest.php

use createMock() instead of deprecated getMock()

---

Resources/views/CRUD/edit_orm_many_to_many.html.twig
Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig

Closes https://github.com/sonata-project/SonataAdminBundle/issues/4533
```markdown
- added the missing `sonata-ba-field-error` class to table fields with errors
```
The class `sonata-ba-field-error` was missing so that sub-forms were not correctly handled when inside a tab here: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/public/Admin.js#L329

[Fix] add missing sonata-ba-field-error class

---

DependencyInjection/SonataDoctrineORMAdminExtension.php

I am targeting this branch, because this is about avoiding deprecation warning.
```markdown
- Replaced `getEntityManager` with `getManager`
```
Since Symfony 2.1 `Registry::getEntityManager()` method is deprecated and should be replaced by `Registry::getManager()`

Fix getEntityManager deprecation

---

Admin/FieldDescription.php
Model/ModelManager.php
Tests/Admin/FieldDescriptionTest.php
Tests/Fixtures/Entity/AssociatedEntity.php
Tests/Model/ModelManagerTest.php

I am targeting this branch, because it's BC bug fix.
```markdown
- Fixed invalid FieldDescription for association embedded properties
```
Without this fix the ModelManager is not able to generate valid FieldDescription for association embedded properties.

Fix invalid FieldDescription for association embedded properties

---

Resources/views/CRUD/edit_orm_one_association_script.html.twig

I am targeting this branch, because it is BC bug fix .
Fixes https://github.com/sonata-project/SonataAdminBundle/issues/4227 for Doctrine ORM
Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/590
```markdown
- Patched collection form handling script to maintain File input state when new items are added to collections
```
When adding items to collection, full form is returned and re-rendered. This update copies over the file input state into the newly fetched form.

Maintain File input state when adding to collections.

---

Model/ModelManager.php
Tests/Fixtures/Entity/SimpleEntity.php
Tests/Model/ModelManagerTest.php

It is deprecated.
Fixes #679, Closes #681
I am targeting this branch, because this is backwards-compatible.
In case of bug fix, `3.x` **MUST** be targeted.
```markdown
- warning about deprecate "e" modifier for `preg_replace`
```

Avoid preg_replace's e modifier

---

Datagrid/ProxyQuery.php
Tests/Datagrid/ProxyQueryTest.php
composer.json

I am targeting this branch, because this is bug fix.
Closes #458, closes #210, closes #694, closes #703
```markdown
- Fix sorting by multiple columns in custom createQuery in PostgreSQL and MySQL 5.7
```
This is continuation of #703. Multiple orderBy in custom createQuery causes errors.
PostgreSQL:
`SQLSTATE[42P10]: Invalid column reference: 7 ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list `
MySQL 5.7 with ONLY_FULL_GROUP_BY mode (which is default):
`SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'mydb.c0_.mycolumn' which is not in SELECT list; this is incompatible with DISTINCT").`
I adapted solution proposed by @jerome-fix and added tests.

Fix sorting by multiple columns in PostgreSQL and MySQL 5.7

---

Datagrid/ProxyQuery.php
Tests/Datagrid/ProxyQueryTest.php
Tests/Fixtures/Query/FooWalker.php

I am targeting this branch, because it is BC feature.
Closes sonata-project/SonataTranslationBundle#162
```markdown
- Added `ProxyQuery::setHint` which allow to pass Query hint in createQuery
```
Right now it is impossible to setHint on Query:
```php
public function createQuery($context = 'list')
{
$proxyQuery = parent::createQuery($context);
$proxyQuery->setHint(
\Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);
return $proxyQuery;
}
```
I would like to reduce number of database queries. Using the TranslationBundle it is additional query per row, as described here sonata-project/SonataTranslationBundle#162. `setHint` has the same syntax as in `Doctrine\ORM\AbstractQuery`.
Let me know what do you think about this idea.

Allow to set Query hint in createQuery

---

composer.json

I am targeting this branch, because it is bugfix.
Closes #731
```markdown
- Change minimum doctrine/orm version to 2.4.5 because QueryBuilder bug on PHP7 and HHVM
```
#730 test case revealed Doctrine bug in version < 2.4.5 on master branch, see #731. But I noticed that 3.x is affected too. Test fail on my local env in 3.x.

Change minimum doctrine/orm version

---

Datagrid/Pager.php
Datagrid/ProxyQuery.php
Model/ModelManager.php
Tests/Model/ModelManagerTest.php

```markdown
- Fixed deprecated method calls
```
This should fix https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/745

Fixed deprecated method calls

---

src/Resources/views/CRUD/edit_orm_one_to_many_inline_tabs.html.twig

When using setSubClasses and using tabs, error is thrown for fields that are not defined in one of the classes.
I am targeting this branch, because using setSubClasses with the inline and sonata_type_collection which uses `edit_orm_one_to_many_inline_tabs.html.twig` throws an error `Key "...." for array with keys "_delete, title, content ...." does not exist `.
```markdown
- don't display fields that are missing in child classes
```

Edit Inline when using sonata_type_collection with SubClasses is throwing error.

---

composer.json
docs/reference/form_field_definition.rst
src/Resources/views/CRUD/edit_orm_many_association_script.html.twig
src/Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because I am adding an additional feature.
Closes #707
```markdown
- Added edit button that opens in dialog instead of add if there is object already in sonata type model list
```
Instead of add button that would replace the current object with a new one, add edit button that would open the current object in dialog instead of redirecting to edit screen of that object.

sonata_type_model_list edit button in dialog

---

src/Builder/FormContractor.php
tests/Builder/FormContractorTest.php

```markdown
- Fix CollectionType on Symfony 3 when no type is specified
```
When creating a CollectionType without specifying its type, `sonata_admin_type` gets used and it does not work. This PR fixes it.

Fix form type FQCN when creating CollectionType

---

src/Builder/DatagridBuilder.php
src/Builder/FormContractor.php
src/DependencyInjection/SonataDoctrineORMAdminExtension.php
src/Filter/AbstractDateFilter.php
src/Filter/BooleanFilter.php
src/Filter/CallbackFilter.php
src/Filter/ChoiceFilter.php
src/Filter/ClassFilter.php
src/Filter/DateFilter.php
src/Filter/DateRangeFilter.php
src/Filter/DateTimeFilter.php
src/Filter/DateTimeRangeFilter.php
src/Filter/ModelAutocompleteFilter.php
src/Filter/ModelFilter.php
src/Filter/NumberFilter.php
src/Filter/StringFilter.php
src/Filter/TimeFilter.php
src/Guesser/FilterTypeGuesser.php
src/Resources/config/doctrine_orm.xml
tests/Builder/FormContractorTest.php
tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php

Removing old code that never gets executed because we dropped SF 2.3 to 2.7

Drop old Symfony code

---

src/Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because it's a non BC bugfix.
```markdown
Allow to `add` a new Model even if one is already selected
```
Introduced with #708 was an additional condition for the `add` button which shouldn't be there. This prevents creating new models if one is already selected. If this behaviour is still needed it can be archived in the Admin::configureFormFields method simply by setting the `btn_add` option to `false`.

sonate_admin.value shouldn't be a condition for the add button

---

src/Resources/views/CRUD/edit_orm_many_association_script.html.twig

I am targeting this branch, because I am adding fix for edit button that was always opening initial item in popup even if you replace that item with list/add action. 
```markdown
- Added refresh of edit button URL if item was replaced by add/list action
- Issue with edit button always showing initial item in popup
```
As pointed out to me in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/765#issuecomment-348928269 by n3o77 if you replace the item with list/add action edit button will still open the initial item in the popup and that is wrong. I added javascript code that is loaded if `btn_edit` is enabled, and it will change the URL of edit button when updating the label.

Refresh edit button URL if item is replaced with list/add action

---

src/Datagrid/ProxyQuery.php
tests/Datagrid/ProxyQueryTest.php

I am targeting this branch, because this is BC fix.
Closes #766
```markdown
- Fixed invalid PathExpression error in ProxyQuery
```
#728 introduced bug in ProxyQuery for tables with composite keys. `ProxyQuery::addOrderedColumns` should skip columns that have already been added to the SELECT as IDENTITY(column).

Fix Invalid PathExpression error in ProxyQuery

---

src/Datagrid/ProxyQuery.php
tests/Admin/FieldDescriptionTest.php
tests/Builder/DatagridBuilderTest.php
tests/Builder/FormContractorTest.php
tests/Builder/ListBuilderTest.php
tests/Datagrid/ProxyQueryTest.php
tests/DependencyInjection/Compiler/AddAuditEntityCompilerPassTest.php
tests/DependencyInjection/Compiler/AddTemplatesCompilerPassTest.php
tests/Filter/ModelFilterTest.php
tests/Guesser/FilterTypeGuesserTest.php
tests/Model/ModelManagerTest.php

I am targeting this branch, because it's BC.
```markdown
- Replaced FQCN strings with `::class` constants
```

Replace FQCN strings with ::class constants

---

src/Builder/DatagridBuilder.php
src/Builder/FormContractor.php
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php
src/Filter/ModelFilter.php
src/Guesser/FilterTypeGuesser.php
src/Guesser/TypeGuesser.php
tests/Datagrid/ProxyQueryTest.php
tests/Filter/ModelFilterTest.php
tests/Model/ModelManagerTest.php

```markdown
- deprecation about `Doctrine\ORM\Mapping\ClassMetadataInfo`
```
This class is deprecated. See https://github.com/doctrine/doctrine2/pull/6886

Replace references to ClassMetadataInfo

---

composer.json
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php
src/Resources/views/CRUD/edit_modal.html.twig
src/Resources/views/CRUD/edit_orm_many_association_script.html.twig
src/Resources/views/CRUD/edit_orm_many_to_many.html.twig
src/Resources/views/CRUD/edit_orm_many_to_one.html.twig
src/Resources/views/CRUD/edit_orm_one_association_script.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many_inline_tabs.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many_sortable_script_table.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many_sortable_script_tabs.html.twig
src/Resources/views/CRUD/edit_orm_one_to_one.html.twig
src/Resources/views/CRUD/list_orm_many_to_many.html.twig
src/Resources/views/CRUD/list_orm_many_to_one.html.twig
src/Resources/views/CRUD/list_orm_one_to_many.html.twig
src/Resources/views/CRUD/list_orm_one_to_one.html.twig
src/Resources/views/CRUD/show_orm_many_to_many.html.twig
src/Resources/views/CRUD/show_orm_many_to_one.html.twig
src/Resources/views/CRUD/show_orm_one_to_many.html.twig
src/Resources/views/CRUD/show_orm_one_to_one.html.twig
src/Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because I am deprecating templates from this bundle and switching to templates in `SonataAdminBundle`
```markdown
- Switched to templates from SonataAdminBundle
- Association templates
```
After ElectricMaxxx mentioned [here](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/770#issuecomment-349443898) that templates were moved to `SonataAdminBundle` I saw that we are still using the ones from `SonataDoctrineORMAdminBundle` so here is the depreciation of old ones and switching to new ones.

Deprecate current templates and start using templates from SonataAdminBundle

---

src/Datagrid/OrderByToSelectWalker.php
src/Datagrid/ProxyQuery.php
tests/Datagrid/OrderByToSelectWalkerTest.php
tests/Datagrid/ProxyQueryTest.php
tests/Fixtures/Entity/ORM/Menu.php
tests/Fixtures/Entity/ORM/Product.php
tests/Fixtures/Entity/ORM/Store.php
tests/Fixtures/Entity/ORM/StoreProduct.php

I am targeting this branch, because it is BC fix.
Closes #776
```markdown
- Fixed invalid PathExpression error in ProxyQuery
```
`ProxyQuery::addOrderedColumns` does not support all syntax variants and operate on an unparsed query. AST walker solves adding missing items from OrderBy to Select problem in the right way. Fix Invalid PathExpression error.

Replace string operation on OrderBy by AST walker

---

src/Builder/FormContractor.php
tests/Admin/FieldDescriptionTest.php

Should fix broken tests since Doctrine 2.6 is out.

Ensure the fieldname is never null

---

src/Builder/FormContractor.php
src/Datagrid/OrderByToSelectWalker.php
src/Datagrid/ProxyQuery.php
tests/Admin/FieldDescriptionTest.php
tests/Datagrid/OrderByToSelectWalkerTest.php
tests/Datagrid/ProxyQueryTest.php
tests/Fixtures/Entity/ORM/Menu.php
tests/Fixtures/Entity/ORM/Product.php
tests/Fixtures/Entity/ORM/Store.php
tests/Fixtures/Entity/ORM/StoreProduct.php

Manual merge

---

src/Builder/ListBuilder.php

I am targeting this branch, because I am fixing an issue.
```markdown
- typo in ListBuilder
```
@pribeirojtm just noticed there was a typo (https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/6846b7a6e44ec2a22779f31b4f3c8ea97cc5002b#r26936534) when I changed templates to SonataAdminBundle. This fixes it.

Fix typo in ListBuilder

---

src/Resources/config/audit.xml

I am targeting this branch, because there is no BC-break.
Closes #801
```markdown
- Symfony 3.4 deprecation notice about getting private service AuditReader from the container
```
Services are private by default in symfony 3.4. AuditReader service is fetched directly from the container in Sonata\AdminBundle\Model\AuditManager::getReader. This action triggers a deprecation notice: The "sonata.admin.audit.orm.reader" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0
Fixes #801

AuditReader service made public to remove Symfony 3.4 deprecation notice

---

src/Datagrid/ProxyQuery.php
tests/Datagrid/ProxyQueryTest.php

```markdown
- `setSortOrder` input is now validated
```

Validate setSortOrder input

---

src/Datagrid/OrderByToSelectWalker.php

I am targeting this branch, because this is BC fix.
```markdown
- Hide selects added by OrderByToSelectWalker from hydration
```
Select expressions added by `OrderByToSelectWalker` should be marked as hidden to prevent pollute query result field set. This class works as expected in ProxyQuery but it can be use in other contexts like https://github.com/sonata-project/SonataAdminBundle/issues/4924.

Hide selects added by OrderByToSelectWalker from hydration

---

src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

I am targeting this branch, because this is BC fix.
```markdown
- Add orderBy field to select list for DataSourceIterator
```
On new version of MySQL fields that are in order by need to be in select list, adding walker `OrderByToSelectWalker` fixes the problem. Fixes https://github.com/sonata-project/SonataAdminBundle/issues/4924

add order by field to select for export

---

composer.json

I am targeting this branch, because this is a patch.
```markdown
- Added doctrine/doctrine-bundle to composer.json
```
Some services from this bundle require `doctrine` service, but there is no `doctrine/doctrine-bundle` in `require` section of composer.json
Also to install AdminBundle and DoctrineORMAdminBundle with Flex, users will have to add doctrine-bundle manualy (recipe is not accepted on this moment):
```
composer create-project symfony/skeleton .
composer config extra.symfony.allow-contrib true
composer require sonata-project/doctrine-orm-admin-bundle doctrine/doctrine-bundle
```

Add doctrine/doctrine-bundle to composer.json

---

composer.json

I am targeting this branch, because this is a patch.
Currently, new tests that I added https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/807 are failing because the minimum version is `0.1`, raising the minimum version of `SimpleThingsEntityAuditBundle` fixes the problem.

Increase dependency of simplethings audit bundle

---

composer.json

Just declared some dependencies that are already on the code, and removed dependency on security, because the only reference to security is ACL. It was added here: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/320 just to replace the main symfony package.

Make composer dependencies explicit

---

composer.json

Closes #557 
This dependency is not used, it was added because an issue with composer: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/556
Probably with PHP 5.6 the dependency resolution is fast enough to remove it.

Remove unused dev dependency

---

src/Builder/DatagridBuilder.php
tests/Builder/DatagridBuilderTest.php

I am targeting this branch, because this is a BC fix.
Closes #788
```markdown
- embedded fields not working as filters
```
Fixes issue where wrong name was used for queries when the field is embedded. (This took a lot of time to debug)

Fix issue with embedded fields as filters

---

docs/tutorial/creating_your_first_admin_class/defining_entities.rst
src/Guesser/FilterTypeGuesser.php
src/Guesser/TypeGuesser.php
tests/Guesser/FilterTypeGuesserTest.php
tests/Guesser/TypeGuesserTest.php

I am targeting this branch, because this a fix for missing "date*_immutable" types.
```markdown
- Support for "datetime_immutable", "datetimetz_immutable", "date_immutable" and "time_immutable" Doctrine types at `TypeGuesser::guessType()` and `FilterTypeGuesser::guessType()`.
- "nl2br() expects parameter 1 to be string, object given" error caused at `base_show_field.html.twig`.
```
Add support for "date*_immutable" types.

Add support for "date*_immutable" types

---

src/Guesser/TypeGuesser.php
tests/Guesser/TypeGuesserTest.php

Closes https://github.com/sonata-project/SonataAdminBundle/issues/3135
```markdown
- Added json_array to type guesser
```

Add json_array to type guesser

---

src/Builder/FormContractor.php
tests/Builder/FormContractorTest.php

Closes https://github.com/sonata-project/SonataAdminBundle/issues/5001
```markdown
- Now it is possible to use entities with arguments on the constructor on the Collection and Admin types.
```
`empty_data` can be used to override the default behavior when an entity does have a constructor with arguments.
http://symfony.com/doc/master/form/use_empty_data.html#option-1-instantiate-a-new-class
We are using the closure because otherwise it will fail on the collectionType. Probably adminType can use it without closure, have to check.
@Soullivaneuh can you check if this fixes your issue?
This is WIP, because we have to check we don't break anything with it.

Entities with construct can be used on Collection and AdminType

---

docs/reference/query_proxy.rst
src/Datagrid/Pager.php
src/Datagrid/ProxyQuery.php
tests/Datagrid/PagerTest.php
tests/Datagrid/ProxyQueryTest.php

List view for big tables very slow due to DISTINCT query.
Also we should have available to enable distinct for query like with left join.
I am targeting this branch, because this is Feature.
Closes #473
```markdown
- Added `ProxyQuery::setDistinct` and `ProxyQuery::isDistinct`.
- `Pager` use `CountWalker` for get count.
```

 #473. Available disable distinct for ProxyQuery and Pager.

---

src/Model/ModelManager.php
tests/Fixtures/Entity/Embeddable/SubEmbeddedEntity.php
tests/Model/ModelManagerTest.php

I am targeting this branch, because it's BC bug fix..
Closes #826 
```markdown
- Fix FieldDescription for multi-level embedded properties
```

Fix FieldDescription for multi-level embedded properties

---

src/Resources/views/Form/form_admin_fields.html.twig

I am targeting this branch, because this PR fixes an issue introduced in commit c961daec5a37f0965d39b33c3b95ef43a60184e2.
```markdown
- Block sonata_type_model_list_widget in template Form/form_admin_fields.html.twig now determines the object identifier correctly when building a link to the associated admin
```
The sonata_type_model_list form type allows for editing the objects associated by providing an edit link for the associated item. However, the code assumes that the identifier field of the object is always called `id`, resulting in exceptions when objects have an identifier with a different name. Since Admin classes have a `getNormalizedIdentifier($object)` method, it seems to make sense to use this instead of hard-coding the identifier field name.

Use getNormalizedIdentifier() to retrieve object identifier

---

src/Resources/config/security.xml

Services are private by default since Symfony 3.4.
I am targeting this branch, because there is no BC-Break.
Closes #846
```markdown
- sonata.admin.manipulator.acl.object.orm is now public
```

Fixes #846

---

src/Resources/views/Form/form_admin_fields.html.twig

…
I am targeting this branch, because I use this version and there is a bug.
Closes issues. I am not aware of any such issues. 
```markdown
- FIx Twig_Error_Runtime  "Key "associationAdmin" for array with keys translationDomain, associationadmin, options" does not exist."
```
Fix Twig_Error_Runtime  "Key "associationAdmin" for array with keys translationDomain, associationadmin, options" does not exist."

Fix Twig_Error_Runtime  "Key "associationAdmin" for array with keys translationDomain, associationadmin, options" does not exist."

---

src/DependencyInjection/Configuration.php
tests/DependencyInjection/ConfigurationTest.php

This is to fix [deprecation for symfony/config 4.2](https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes)+
I am targeting this branch, because is the one with this warning.
```markdown
Fix deprecation for symfony/config 4.2+
```
I added the ConfigurationTest class, but I wasn't sure what to test 😬so I used https://github.com/sonata-project/SonataAdminBundle/blob/3.x/tests/DependencyInjection/ConfigurationTest.php as an example.
The fix is like https://github.com/doctrine/DoctrineBundle/pull/853

Fix deprecation for symfony/config 4.2+

---

docs/reference/form_field_definition.rst
src/Builder/FormContractor.php
tests/Builder/FormContractorTest.php

If you use the new `Sonata\Form\Type\CollectionType` it doesn't show the fields properly in the form because the new namespace it is not checked in `FormContractor`. I guess the same happens in the MongoDB and Phpcr Bundle.
I am targeting this branch, because is this is a patch.
```markdown
- Fixed using the new collection type namespace
```

Fix deprecated_collection_type

---

src/Filter/StringFilter.php
tests/Filter/StringFilterTest.php

this change is needed to make a filter `case-insensitive` instead of `case-sensitive`
Refs https://github.com/sonata-project/SonataAdminBundle/pull/5353
```markdown
- Added possibility to make `StringFilter` case-insensitive
```

added case_sensitive option to StringFilter

---

src/DependencyInjection/Configuration.php
src/Model/ModelManager.php

This function is not in the whitelist of functions benefiting from it.
See https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/6f2c266440de15e23a82788e598ea66521ed60b2/src/Fixer/FunctionNotation/NativeFunctionInvocationFixer.php#L338

Remove useless backslash

---

src/Model/ModelManager.php

I opened an issue in SonataAdminBundle with the problem, you can see from this link:
https://github.com/sonata-project/SonataAdminBundle/issues/5448
In this pull request I include (string) cast to avoid TypeError with explode function.
I am targeting this branch, because in this branch is included strict_types.
Closes https://github.com/sonata-project/SonataAdminBundle/issues/5448
```markdown
TypeError with explode in ModelManager
```

include string cast to avoid typeError with explode function

---

src/Datagrid/Pager.php
tests/Datagrid/PagerTest.php
tests/Fixtures/Entity/ORM/User.php
tests/Fixtures/Entity/ORM/UserBrowser.php

To preserve the feature from #827 but still revert to the old way for count calculate.
Closes #834 
```markdown
- Composite key pagination throwing exception
```

Revert support for composite key in Pager

---

src/Datagrid/ProxyQuery.php

|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |no    |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |

Remove call to `call_user_func_array()` at `ProxyQuery::__call()`

---

src/Datagrid/Pager.php
tests/Datagrid/PagerTest.php

```markdown
- `Sonata\DoctrineORMAdminBundle\Datagrid\Pager::computeNbResult()` now returns an integer, not a string
```

Applied fixes from FlintCI

---

src/Filter/StringFilter.php
tests/Filter/StringFilterTest.php

Since the project is now using strict_types send null value to the trim function would cause an exception. To fix that a check for null value inside  was added.
I am targeting this branch, because the strict types are not being used in 2.x.
Closes #900
```markdown
- Added check for null value to prevent exception on StringFilter
```

Prevent trim function to be executed with null value on StringFilter

---

src/Model/ModelManager.php
tests/Fixtures/Entity/ProtectedEntity.php
tests/Model/ModelManagerTest.php

I am targeting this branch, because this feature is BC.
```markdown
- Added support for protected (no public constructor) entity creation
```

Check if constructor is callable when creating new model instance

---

src/Model/ModelManager.php
tests/Fixtures/DoctrineType/UuidBinaryType.php
tests/Model/ModelManagerTest.php

Solution for [#923](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/923).
While a more elegant solution is found for this case, this PR would fix the errors when generating URLs in Sonata Admin when using entities with composite and foreign keys. See manual of doctrine: [Link](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/composite-primary-keys.html)
Closes #923 
```markdown
- Fix "Resolve string value of is with __toString cause trouble with composite key" (#923)
```

Resolve error in entities with composite ID

---

src/Model/ModelManager.php
tests/Fixtures/DoctrineType/ProductIdType.php
tests/Fixtures/Entity/Product.php
tests/Fixtures/Entity/ProductId.php
tests/Model/ModelManagerTest.php

Fix a break BC error
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/928#issuecomment-520774529
DoctrineTypeMapping contain only internal types. Trying to get a custom type in [this](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L637) place will always result in error.
```php
array (
'tinyint' => 'boolean',
'smallint' => 'smallint',
'mediumint' => 'integer',
'int' => 'integer',
'integer' => 'integer',
'bigint' => 'bigint',
'tinytext' => 'text',
'mediumtext' => 'text',
'longtext' => 'text',
'text' => 'text',
'varchar' => 'string',
'string' => 'string',
'char' => 'string',
'date' => 'date',
'datetime' => 'datetime',
'timestamp' => 'datetime',
'time' => 'time',
'float' => 'float',
'double' => 'float',
'real' => 'float', …
```

Сheck platform type is exists before get it

---

src/Datagrid/Pager.php
tests/Datagrid/PagerTest.php

I wrote a custom filter with Having/groupBy condition and got an exception when no result was found.
This was the query
```
SELECT count(DISTINCT a0_.id) AS sclr_0 FROM asv_contract a0_ LEFT JOIN asv_relaunch a1_ ON a0_.id = a1_.contract_id LEFT JOIN asv_client_role a2_ ON a0_.id = a2_.contract_id LEFT JOIN asv_external_client_id a3_ ON a2_.external_client_id = a3_.id LEFT JOIN asv_client a4_ ON a3_.client_id = a4_.id WHERE a4_.usagename LIKE ? GROUP BY a0_.id, a0_.admin_comment, a0_.external_contract_id, a0_.effective_date, a0_.end_date, a0_.updated_date, a0_.sent_to_partner_date, a0_.created_by_grc_date, a0_.completed_by_grc_date, a0_.pledge, a0_.management_mandate, a0_.contract_status, a0_.buy_worth, a0_.initial_amount, a0_.current_advances, a0_.is_investor_profile_ignored, …
```

Avoid exception when no result

---

tests/Datagrid/ProxyQueryTest.php
tests/Fixtures/Entity/DoubleNameEntity.php

The bridge archived have recently been modified so that they no longer
contain tests. We were relying on one of the fixtures that came with
this tests. Copying the fixture to our project fixes the issue.
Fixes the build when using Symfony 4.4 or 5.0.
See https://github.com/symfony/doctrine-bridge/commit/bfe0b2925359c956da692252b9b5f38cd98ab585#diff-fc723d30b02a4cca7a534518111c1a66

Steal fixture from the Doctrine bridge

---

src/Datagrid/ProxyQuery.php

Query builder is annotated as QueryBuilder in all other places, except here. This will help developers when altering queries (e.g. in filters), because the IDE will autocomplete properly and also static analysers like PHPStan will not complain (correctly).
I am targeting this branch, because this is a fix, should be BC.
```markdown
- Fix ProxyQuery::getQueryBuilder() return type.
```

Fix ProxyQuery::getQueryBuilder() return type

---

src/Filter/BooleanFilter.php
src/Filter/ChoiceFilter.php
src/Filter/ClassFilter.php
tests/Filter/BooleanFilterTest.php
tests/Filter/CallbackFilterTest.php
tests/Filter/ChoiceFilterTest.php
tests/Filter/ClassFilterTest.php

I am targeting this branch, because there is no breaking changes.
```markdown
`operator_type` and `operator_options` are overridable for the provided Filters
```

Allow to override Operator option

---

src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

Avoid to call not accessible `toString()` methods.
Related to #937.
```markdown
- Avoid to call not accessible `toString()` methods.
```

Avoid to call not accessible `toString()` methods

---

composer.json
src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

A backwards-compatibility layer has been added to persistence to help
consumers move to the new namespacing. It is based on class aliases,
which means the type declaration changes should not be a BC-break: types
are the same.
See doctrine/persistence#71
This means:
- using the new namespaces
- adding autoload calls for new types to types that may be extended and
use persistence types in type declarations of non-constructor methods,
so that signature compatibility is recognized by old versions of php.
Luckily, there were none of these in this package.
More details on this at
https://dev.to/greg0ire/how-to-deprecate-a-type-in-php-48cf

Address future deprecations from doctrine/persistence

---

composer.json
src/Resources/config/doctrine_orm.xml

Leverage "sonata.admin.manager" service tag
Closes #924.
```markdown
- "sonata.admin.manager" tag to "sonata.admin.manager.orm" service.
```

Leverage "sonata.admin.manager" service tag

---

src/Model/ModelManager.php

Not overwrite the entity metadata on get the identifier metadata in `ModelManager::getIdentifierValues()`
Critical error here:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L351
You overwrite the entity metadata variable on get the identifier metadata and in the next itarations we tring get metadata from previous identifier, not a entity metadata.
```php
public function getIdentifierValues($entity)
{
$class = ClassUtils::getClass($entity);
// Entity metadata!!!
$metadata = $this->getMetadata($class);
$platform = $this->getEntityManager($class)->getConnection()->getDatabasePlatform();
$identifiers = [];
foreach ($metadata->getIdentifierValues($entity) as $name => $value) {
if (!\is_object($value)) {
$identifiers[] = $value;
continue;
} …
```

Breaks if entity has many identifiers and one of the not last identifiers is an entity

---

tests/Block/AuditBlockServiceTest.php
tests/DependencyInjection/ConfigurationTest.php

I am targeting this branch, because it is a BC.
I tried using Rector, by using
```
composer require rector/rector-prefixed phpunit/phpunit --dev
vendor/bin/rector process tests --set phpunit90 --dry-run
```
You can see the output here: [rector_output.txt](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/files/4232688/rector_output.txt)
Then I had a look and saw why it does not help: https://github.com/rectorphp/rector/blob/master/config/set/phpunit/phpunit90.yaml
So I ended up doing the changes manually.

Address PHPUnit's warnings

---

src/Guesser/TypeGuesser.php
tests/Guesser/TypeGuesserTest.php

Doctrine has 4 array types: array, simple_array, json and json_array (see https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/types.html).
TypeGuesser currently only supports array, json and json_array.
This PR adds support for simple_array.
I am targeting this branch, because there is no backwards compatibility issue.
```markdown
- Added support for guessing the show type of `simple_array` fields.
```

Add support for simple_array type to TypeGuesser

---

src/Datagrid/ProxyQuery.php
tests/Datagrid/ProxyQueryTest.php

I am targeting this branch, because I don't consider this like a BC-break but like a bug fix.
When adding
```
$query->addOrderBy()
```
In the `createQuery` function of an Admin class, the `orderBy` clauses was applied before the `sort_by` parameter of the datagrid value. Which break the behaviour of the list orders.
But in this situation I expect the opposite behaviour
- The list is first ordered by the selected column
- In case of row with the same values, the `orderBy` in the createQuery is used.
```markdown
The `_sort_by_ ` datagrid value is properly applied before any custom `orderBy`.
```

use SortBy before custom orderBy

---

src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

Following https://github.com/sonata-project/SonataAdminBundle/issues/5929, I want to introduce the ability of using `sortable => true` without a default column to sort the list.
This means that `$value['_sort_by']` can be 'not set'. 
```markdown
Allow `_sort_by` filter to not be initially defined. 
```

Handle case without sort_by value

---

src/Filter/ChoiceFilter.php
tests/Filter/ChoiceFilterTest.php
tests/Filter/QueryBuilder.php

Closes #991
```markdown
- allow null to be selected in ChoiceFilter
```

allow null selection in ChoiceFilter

---

src/Guesser/FilterTypeGuesser.php
tests/Guesser/FilterTypeGuesserTest.php

Closes #1008
```markdown
change field type in Filter Guesser for integer
```

correct field type for integer in Filter Guesser

---

src/Filter/ChoiceFilter.php
tests/Filter/ChoiceFilterTest.php

I am targeting this branch, because unfortunally this is a BC-break.
The `all` special case make no sens to me.
- It's not documented
- I can't filter by the `all` value if I have the `all` value in database.
- It does nothing, it's the same than an empty input.
```markdown
- Special case for the `all` value in ChoiceFilter
```
If accepted, I'll make the PR for the other ORM bundle.

Remove choice filter 'all' special case

---

src/Builder/FormContractor.php
tests/Builder/FormContractorTest.php
tests/Model/ModelManagerTest.php

I am targeting this branch, because since Sf2.8 is dropped, it's BC.
```markdown
Code used for 2.8 symfony support
```

Remove some NEXT_MAJOR in stable branch !

---

src/Model/ModelManager.php

I am targeting this branch, because BC-break.
Related to https://github.com/sonata-project/SonataAdminBundle/issues/5929#issuecomment-599215849
```markdown
- The modelManager getDefaultSortValues does not have default _sort_by value anymore.
```

Stop using default _sort_by

---

src/Datagrid/Pager.php
tests/Datagrid/PagerTest.php
tests/Fixtures/Entity/ORM/User.php
tests/Fixtures/Entity/ORM/UserBrowser.php

Closes #497
```markdown
- Concat value of complex primary key for correct calculate total pages in Datagrid
```

Concat value of complex primary key for correct calculate total pages in Datagrid

---

src/Datagrid/Pager.php

Save extra processing at `Pager::countCompositePrimaryKey()`.
Related to #996.

Save extra processing at `Pager::countCompositePrimaryKey()`

---

src/Model/ModelManager.php

Add explicit `null` return values at `ModelManager::getNormalizedIdentifier()`.
```markdown
- Fixed returning `void` in `ModelManager::getNormalizedIdentifier()`, which is intended to return a value or `null`.
```

Add explicit `null` return values at `ModelManager::getNormalizedIdentifier()`

---

src/Model/ModelManager.php

```markdown
- Deprecate `getModelIdentifier` from `ModelManager`
```

Deprecate getModelIdentifier

---

src/Admin/FieldDescription.php

FieldDescription.php contained an outdated link to a Doctrine documentation page.
I am targeting this branch, because it's a comment.

Fix a link to Doctrine documentation site

---

src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

Fix type check at `ModelManager::getNormalizedIdentifier()`.
```markdown
- Fixed weak check at `ModelManager::getNormalizedIdentifier()`.
```

Fix type check at `ModelManager::getNormalizedIdentifier()`

---

src/Model/ModelManager.php

Fix camel case for `ModelManager::getUrlSafeIdentifier()` method.

Fix camel case for `ModelManager::getUrlSafeIdentifier()` method

---

src/Filter/AbstractDateFilter.php
tests/Filter/DateFilterTest.php

v3.15 introduced a bug because of a typo in AbstractDateFilter, referencing Sonata\AdminBundle\Form\Type\Operator\DateRangeOperatorType::TYPE_EQUAL, where it should have been Sonata\AdminBundle\Form\Type\Operator\DateOperatorType::TYPE_EQUAL.
I am targeting this branch, because this bug has been recently introduced in 3.15 and affects everyone downloading the latest version of Sonata.
```markdown
Typo in AbstractDateFilter, DateRangeOperatorType::TYPE_EQUAL should have been DateOperatorType::TYPE_EQUAL.
```

Fix typo in AbstractDateFilter which can lead to exceptions

---

src/Model/ModelManager.php

Related to https://github.com/sonata-project/SonataAdminBundle/pull/6069
This will allow the ModelManager to respect the 4.0 interface.
```markdown
- Added `ModelManager::getDefaultPerPageOptions`
```

Add getDefaultPerPageOptions

---

composer.json
src/Resources/views/CRUD/edit_orm_one_to_many_inline_tabs.html.twig

Remove Twig deprecated syntax `for..if`.
```markdown
- Added direct dependency against "twig/twig".
- Fixed usage of deprecated Twig syntax `for..if`.
```

Remove Twig deprecated syntax `for..if`

---

docs/reference/filter_field_definition.rst
src/Filter/StringListFilter.php
tests/Filter/StringListFilterTest.php

This filter allow to search for specific value when you use `@ORM\Column(type="array")`.
Let's say you have in database
1 => ['a']
2 => ['b']
3 => ['c']
4 => ['a', 'b']
5 => ['a', 'c']
6 => ['a', 'b', 'c']
If you search
-  CONTAINS `['a']` ; you'll get 1,4,5,6.
-  NOT CONTAINS `['a']` ; you'll get 2,3.
-  EQUAL `['a']` ; you'll get 1.
-  CONTAINS `['a', 'b']` ; you'll get 4,6.
-  NOT CONTAINS `['a', 'b']` ; you'll get 3.
-  EQUAL `['a', 'b']` ; you'll get 4.
Closes #1029
```markdown
- `ArrayFilter` which supports `@ORM\Column(type="array")`
```

Add Array filter to search value in `@ORM\Column(type="array")`

---

src/Filter/StringFilter.php
tests/Filter/StringFilterTest.php

```markdown
- StringFilter now correctly takes the `case_sensitive` option into account when the operator is `=`.
```

Fix StringFilter with equal operator and case sensitive false

---

composer.json
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php
src/Guesser/FilterTypeGuesser.php
src/Guesser/TypeGuesser.php
tests/Builder/ShowBuilderTest.php

There is no template for types like `number` or `orm_one_to_many`.
So I added a mapping between wrong types and right types to use, only if the developer didn't added a template.
```markdown
- `decimal` and `float` type use the `float` template if no `number` template exists
- `one_to_one`, `one_to_many`, `many_to_one` and `many_to_many` type are correctly using the template defined in your config instead of the Sonata one.
```

Improve Template mapping

---

tests/Builder/FormContractorTest.php

Fix tests after drop SonataCoreBundle.
I am targeting this branch, because it is PATCH.

Fix test after drop CoreBundle

---

UPGRADE-3.x.md
src/Admin/FieldDescription.php
src/Builder/DatagridBuilder.php
src/Builder/FormContractor.php
src/Model/ModelManager.php
tests/Admin/FieldDescriptionTest.php
tests/Builder/FormContractorTest.php
tests/Model/ModelManagerTest.php

Add some deprecations at `ModelManager` and `FieldDescription` in order to be prepared for the next major.
```markdown
- Added `FieldDescription::getTargetModel()`.
- Deprecated passing `null` as argument 2 for `ModelManager::find()`;
- Deprecated passing `null` as argument 1 for `ModelManager::getNormalizedIdentifier()`;
- Deprecated passing objects which are in state 2 (new) or 4 (removed) as argument 1 for `ModelManager::getNormalizedIdentifier()`;
- Deprecated passing other type than `object` as argument 1 for `ModelManager::getUrlSafeIdentifier()`;
- Deprecated `FieldDescription::getTargetEntity()` in favor of `FieldDescription::getTargetModel()`.
```

Add some deprecations about invalid values

---

composer.json
src/Filter/StringFilter.php
tests/Filter/StringFilterTest.php

Provides fix for:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/943#issuecomment-641258617
I am targeting this branch, because its a new feature.
Provides fix for:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/943#issuecomment-641258617
```markdown
- Add `StringFilter` support for `START_WITH` and `END_WITH` operator
```

Add StringFilter support for START_WITH and END_WITH operator

---

docs/reference/filter_field_definition.rst
src/Filter/EmptyFilter.php
src/Resources/config/doctrine_orm_filter_types.xml
tests/Filter/EmptyFilterTest.php

This filter allows filtering for (non-)nullable fields.
```markdown
-  Add new filter for empty fields
```

Add new filter for empty fields

---

src/Block/AuditBlockService.php
src/Resources/config/audit.xml
tests/Block/AuditBlockServiceTest.php
tests/Block/DeprecatedAuditBlockServiceTest.php
tests/DependencyInjection/ConfigurationTest.php
tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php

```markdown
- Passing a string as argument 1 when instantiating Sonata\DoctrineORMAdminBundle\Block\AuditBlockService 
```

Prepare support for BlockBundle 4

---

src/Builder/FormContractor.php
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php
src/DependencyInjection/Compiler/AddAuditEntityCompilerPass.php
src/Filter/AbstractDateFilter.php
src/Filter/ClassFilter.php
src/Filter/ModelFilter.php
src/Filter/NumberFilter.php
src/Filter/StringFilter.php
tests/Builder/DatagridBuilderTest.php
tests/Builder/ListBuilderTest.php
tests/Builder/ShowBuilderTest.php

I wanted to add typehint on the master branch, but some can be added on 3.x.
Plus, `willReturn()` throw an error when the return typehint is `void`. So I modified the tests to prevent this issue.
I am targeting this branch, because pedantic.

Add typehint for private methods and improve tests

---

UPGRADE-3.x.md
src/Filter/StringFilter.php
tests/Filter/StringFilterTest.php

I already found weird the `format` option of the `StringFilter`.
If I look for something containing `foo`, there is IMHO no multiple way to check for this. It always `LIKE %foo%`.
Now, this option is weirder since we have the `START WITH` and an `END WITH` checks.
Why would these checks be made with `%foo` and `foo%` but the CONTAINS one could use another format than `%foo%` ?
That's why I think we should deprecate the `format` option and remove it in the next major.
```markdown
- `format` option of the `StringFilter`.
```

Add deprecation for StringFilter format option

---

composer.json
src/Resources/views/CRUD/edit_modal.html.twig
src/Resources/views/CRUD/edit_orm_many_association_script.html.twig
src/Resources/views/CRUD/edit_orm_many_to_many.html.twig
src/Resources/views/CRUD/edit_orm_many_to_one.html.twig
src/Resources/views/CRUD/edit_orm_one_association_script.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many_inline_tabs.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many_sortable_script_table.html.twig
src/Resources/views/CRUD/edit_orm_one_to_many_sortable_script_tabs.html.twig
src/Resources/views/CRUD/edit_orm_one_to_one.html.twig
src/Resources/views/CRUD/list_orm_many_to_many.html.twig
src/Resources/views/CRUD/list_orm_many_to_one.html.twig
src/Resources/views/CRUD/list_orm_one_to_many.html.twig
src/Resources/views/CRUD/list_orm_one_to_one.html.twig
src/Resources/views/CRUD/show_orm_many_to_many.html.twig
src/Resources/views/CRUD/show_orm_many_to_one.html.twig
src/Resources/views/CRUD/show_orm_one_to_many.html.twig
src/Resources/views/CRUD/show_orm_one_to_one.html.twig

Ref: https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/373
```markdown
- Use `deprecated` tag instead of `sonata_template_deprecate` to not throw unwanted deprecation notices.
- Support for Twig 1.x
```

Use deprecated tag instead of sonata_template_deprecate

---

UPGRADE-3.x.md
composer.json
src/Model/ModelManager.php
src/Resources/config/doctrine_orm.xml
tests/Model/ModelManagerTest.php

Related to https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/368#discussion_r460404367
```markdown
- deprecate `ModelManager::camelize`.
```

Use propertyAccessor and deprecate camelize

---

src/Model/ModelManager.php

Related to https://github.com/sonata-project/SonataAdminBundle/pull/6234
The method wasn't even working so there is no real need for an upgrade note.
```markdown
- Deprecate ModelManager::getParentFieldDescription with no replacement
```

Deprecate getParentFieldDescription

---

src/Resources/views/Form/form_admin_fields.html.twig

**Fix for the Exception:**
Block "sonata_help" on template "form_div_layout.html.twig" does not exist.
**Deprecation message:**
The "sonata_help" option is deprecated since sonata-project/admin-bundle 3.60, to be removed in 4.0. Use "help" instead.
I am targeting this branch, because this branch gives an exception.
```markdown
- Changed `{{ block('sonata_help') }}` to `{{ form_help(form) }}` in `form_admin_fields.html.twig`.
```

Remove sonata_help block

---

docs/reference/form_field_definition.rst
tests/Admin/FieldDescriptionTest.php

Those methods are from `Sonata\AdminBundle\Admin\BaseFieldDescription`, we shouldn't test them here.

Remove references to deprecated help option

---

UPGRADE-3.x.md
composer.json
src/Block/AuditBlockService.php

I am targeting this branch, because this change have to be in 3.x - see https://github.com/sonata-project/SonataAdminBundle/pull/6212.
```markdown
- Add support for SonataBlockBundle 4.0
```

Add support for SonataBlockBundle 4.x

---

composer.json

Allow some symfony/* dependencies to use version ^5.1, since these major versions don't have breaking changes. See:
* https://github.com/symfony/options-resolver/blob/v5.0.0/CHANGELOG.md#500;
* https://github.com/symfony/property-access/blob/v5.0.0/CHANGELOG.md.
Depends on sonata-project/SonataAdminBundle#6299, sonata-project/SonataBlockBundle#730.
```markdown
- Added support for symfony/options-resolver:^5.1;
- Added support for symfony/property-access:^5.1.
```

Allow some symfony/* dependencies to use version ^5.1

---

src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

These methods are deprecated in Sonata Admin.
```markdown
- Deprecate ModelManager collections methods.
- Deprecate ModelManager::getPaginationParameters().
- Deprecate ModelManager::getSortParameters().
```

Add deprecations for ModelManager methods

---

src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

Related to https://github.com/sonata-project/SonataAdminBundle/issues/6273
```markdown
- `ModelManager::supportsQuery()` method
- Calling `executeQuery` on something else than an instance of `Doctrine\ORM\QueryBuilder` or `Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery`.
```

Add supportQuery

---

.github/workflows/qa.yaml
.phpstan/phpstan-baseline.neon
.phpstan/phpstan.neon.dist
src/Util/ObjectAclManipulator.php

When adding phpstan, I also discovered a `Variable $objectIdIterator might not be defined.` error.
```markdown
- Fix null error in `ObjectAclManipulator`
```

Add phpstan to CI

---

composer.json
phpstan-baseline.neon

The most recent phpstan version has made some adjustments, so you can't ignore undefined classes anymore:
```
Class Symfony\Component\Templating\EngineInterface not found.  
```

Fix phpstan build

---

tests/Builder/DatagridBuilderTest.php
tests/Builder/ListBuilderTest.php
tests/Builder/ShowBuilderTest.php
tests/DependencyInjection/Compiler/AddGuesserCompilerPassTest.php
tests/Guesser/FilterTypeGuesserTest.php
tests/Guesser/TypeGuesserTest.php
tests/Model/AuditReaderTest.php
tests/SonataDoctrineORMAdminBundleTest.php

Similar to what I did on SonataAdminBundle.
The templating dependency is needed on require-dev to pass phpstan

Replace prophesize with regular phpunit mocks

---

src/Builder/FormContractor.php
tests/Builder/FormContractorTest.php

Related to https://github.com/sonata-project/SonataAdminBundle/pull/6438
Then I'll need a release to add a conflict on SonataAdmin.
```markdown
- `FormContractor::getDefaultOptions()` now pass `by_reference` from `CollectionType` to `AdminType`
```

Pass option by_reference in case we're using AdminType

---

UPGRADE-3.x.md
docs/reference/filter_field_definition.rst
src/Filter/CallbackFilter.php
tests/Filter/CallbackFilterTest.php

```markdown
- Using a callback filter with a callback option which does not return a boolean
```

Add deprecation if callback return type is not a boolean

---

src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

Throw exception if array passed as argument 3 to `ModelManager::addIdentifiersToQuery()` is empty.
I am targeting this branch, because if the query produced by this method is executed, an exception is already thrown.
Related to sonata-project/SonataAdminBundle#6508.
```markdown
- Check to guarantee that argument 3 passed to `ModelManager::addIdentifiersToQuery()` is not an empty array.
```

Throw exception if array passed as argument 3 to `ModelManager::addIdentifiersToQuery()` is empty

---

src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

Cast the value as string before calling `explode()` at `ModelManager::addIdentifiersToQuery()`.
```markdown
- `TypeError` thrown by `explode()` when receiving non string values as argument 2 from argument 3 at `ModelManager::addIdentifiersToQuery()`.
```

Cast the value as string before calling `explode()` at `ModelManager::addIdentifiersToQuery()`

---

UPGRADE-4.0.md
src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1160
A global option can still be implemented, but IMHO `show` has more sens than `edit` for the default route name.
If accepted, the same PR should be done to https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle

Change default route name for association links to show.

---

composer.json
src/Admin/FieldDescription.php
src/Model/ModelManager.php
tests/Admin/FieldDescriptionTest.php
tests/Builder/DatagridBuilderTest.php
tests/Builder/ListBuilderTest.php
tests/Builder/ShowBuilderTest.php
tests/Model/ModelManagerTest.php

BC
```markdown
- Instantiate a FieldDescription without passing the name as first argument
```

Remove fieldDescription deprecation

---

src/Filter/AbstractDateFilter.php
tests/Filter/DateRangeFilterTest.php

Fix how dates from `DateRangeType` are handled by `DateRangeFilter`.
When the `DateRangeType` uses different values between "view_timezone" and "model_timezone" options, the values that are processed by `AbstractDateFilter::filter()` are `\DateTime` objects (start and end) holding the same timestamp than the view data, but represented in the timezone configured for the model data (thus, the offset of these objects is set to the model timezone and the date and time references are adjusted accordingly).
Previous to this commit, these date and time conversions were becoming imprecise since the `\DateTime` objects used in the filter were being manipulated to set the time part to "00:00:00" (in case of start) and to "23:59:59" (in case of end), which produces wrong results given the offset …

Fix date handling through `DateRangeFilter`

---

src/Resources/views/Form/form_admin_fields.html.twig

In next major of **SonataAdminBundle** only object will be allowed as argument for the `id` method, so we need to skip calling this method without object.

Fix not to call an id method without object.

---

src/Filter/AbstractDateFilter.php
tests/Filter/DateRangeFilterTest.php

Add support for `\DateTimeImmutable` at `AbstractDateFilter::filter()`.
```markdown
- Support for `\DateTimeImmutable` at `AbstractDateFilter::filter()`.
```

Add support for `\DateTimeImmutable` at `AbstractDateFilter::filter()`

---

src/Builder/DatagridBuilder.php

This code is not useful (with the next SonataAdmin release) but we won't be allowed to remove it before next major in order to be BC.

Add Next major comment related to https://github.com/sonata-project/SonataAdminBundle/pull/6578

---

src/Model/ModelManager.php

Remove the exception in `getNormalizedIdentifier`, because of allow `null` as return type for `getUrlSafeIdentifier`, `getNormalizedIdentifier` and `id` in **SonataAdmin**.
I am targeting this branch, because of BC.

Remove the exception and allow return null

---

UPGRADE-3.x.md

Add missing upgrade note for #1190.
I am targeting this branch, because this change does not affect BC.
Related to #1190.
I'm not adding a changelog about this change since the related PR is not present in any release yet.

Add upgrade note for #1190

---

composer.json
src/Builder/FormContractor.php
tests/Builder/FormContractorTest.php

I am targeting this branch, because bug fix.
`by_reference` had conflict with the symfony option, so SonataAdmin change the name of the option.
Close https://github.com/sonata-project/SonataAdminBundle/issues/6564
```markdown
- `FormContractor::getDefaultOptions()` passes `collection_by_reference` option instead of `by_reference` to `AdminType` in order to respect the new API
```

Pass collection_by_reference instead of by_reference

---

composer.json
src/Filter/StringFilter.php
tests/Filter/StringFilterTest.php

```markdown
- Added "Not equal" filter for `StringFilter`
```

Add NOT_EQUAL support for StringFilter

---

docs/reference/filter_field_definition.rst
src/Filter/StringFilter.php
tests/Filter/StringFilterTest.php

If the filter value is empty, but the filtering type has been changed from the default value, then this is an indication that the user wants to search by empty value.
We filter by empty value if the filtering type is explicitly specified.
Part of fix for https://github.com/sonata-project/SonataAdminBundle/issues/3569.
```markdown
- Allow empty string for filtering
```

Allow empty string for filtering

---

UPGRADE-3.x.md
src/Model/ModelManager.php

Remove the deprecation in `getNormalizedIdentifier`, because of allow null as return type for `getUrlSafeIdentifier`, `getNormalizedIdentifier` and `id` in **SonataAdmin**.

Remove the deprecation from getNormalizedIdentifier

---

docs/reference/filter_field_definition.rst
src/Filter/EmptyFilter.php
tests/Filter/EmptyFilterTest.php

I'm adding a `inverse` option in order to use the EmptyFilter as a NotEmptyFilter.
You may want to have a filter called `Has foo`, instead of a `Has no foo` one.
```markdown
- Added an option `inverse` for the EmptyFilter.
```

Add NotEmptyFilter

---

src/Exporter/DataSource.php
src/Resources/config/doctrine_orm.xml
tests/Exporter/DataSourceTest.php

This is the ORM implementation of https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Exporter/DataSourceInterface.php
This will should be automatically injected thanks to https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L275
```markdown
- Added `DataSourceInterface` implementation
```

Add DataSource

---

UPGRADE-3.x.md
composer.json
src/Filter/AbstractDateFilter.php
src/Filter/BooleanFilter.php
src/Filter/CallbackFilter.php
src/Filter/ChoiceFilter.php
src/Filter/ClassFilter.php
src/Filter/EmptyFilter.php
src/Filter/Filter.php
src/Filter/ModelAutocompleteFilter.php
src/Filter/ModelFilter.php
src/Filter/NumberFilter.php
src/Filter/StringFilter.php
src/Filter/StringListFilter.php
src/Model/ModelManager.php

The method `filter` won't be in the interface anymore so we can restrict the typehint.
```markdown
- Deprecate passing an instance of `ProxyQueryInterface` which is not an instance of `Sonata\DoctrineORMAdminBundle\Datagrid::ProxyQuery` as argument 1 to the `Sonata\DoctrineORMAdminBundle\Filter\Filter::filter()` method.
```

Add deprecation for filter method

---

UPGRADE-3.x.md
docs/reference/filter_field_definition.rst
src/Filter/EmptyFilter.php
src/Filter/NullFilter.php
tests/Filter/NullFilterTest.php

Closes #1208.
```markdown
- Added `Sonata\DoctrineORMAdminBundle\Filter\NullFilter`
- Deprecated `Sonata\DoctrineORMAdminBundle\Filter\EmptyFilter`
```

Deprecate EmptyFilter in favor of NullFilter

---

src/Filter/EmptyFilter.php

Fix deprecation of EmptyFilter

---

composer.json
src/Admin/FieldDescription.php
src/Builder/DatagridBuilder.php
src/Builder/FormContractor.php
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php
src/Model/ModelManager.php
tests/Admin/FieldDescriptionTest.php
tests/Builder/DatagridBuilderTest.php
tests/Builder/FormContractorTest.php
tests/Builder/ListBuilderTest.php
tests/Builder/ShowBuilderTest.php
tests/Model/ModelManagerTest.php

Closes #1230.
```markdown
- Deprecated `ModelManager::getMetadata()` method.
- Deprecated `ModelManager::hasMetadata()` method.
```

Stop using deprecated FieldDescription methods

---

UPGRADE-3.x.md
src/Model/ModelManager.php
tests/Model/ModelManagerTest.php

Similar to https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/473
```markdown
- Deprecate `Sonata\DoctrineORMAdminBundle\Model\ModelManager::modelTransform()` with no replacement.
- Deprecate `Sonata\DoctrineORMAdminBundle\Model\ModelManager::getDefaultPerPageOptions()` with no replacement.
- Deprecate `Sonata\DoctrineORMAdminBundle\Model\ModelManager::getDefaultSortValues()` with no replacement.
- Deprecate `Sonata\DoctrineORMAdminBundle\Model\ModelManager::getDataSourceIterator()` with no replacement.
```

Add deprecation for method removed from the interface

---

composer.json
src/Admin/FieldDescription.php
src/Builder/DatagridBuilder.php
src/Model/ModelManager.php
tests/Admin/FieldDescriptionTest.php

I am targeting this branch, because the wrong field name is a bug, so this PR would be a bug fix.
When using the following code 
```
->add('foo.bar')
```
If the subject has a relation to a Foo entity, which has a relation to a Bar entity, the fieldDescription has the following data:
- fieldName: bar
- parentAssociationMapping: An array containing foo.
If it's an embedded entity, the fieldDescription had the following data:
- fieldName: bar
- no parentAssociationMapping.
That's why the there was extra code for embedded fields.
- in getValue
- in fixFieldDescription
But both of these code could be avoid if we correctly set the fieldDescription fieldName when looking for parentAssociationMapping. I propose to change this to:
- fieldName: foo.bar
- no parentAssociationMapping.
Then, no code …

Set the correct fieldName to get the correct value

---

composer.json
src/Datagrid/Pager.php
tests/Datagrid/PagerTest.php

```markdown
- implemented `Sonata\AdminBundle\Datagrid\PagerInterface::countResults()`
- `Sonata\DoctrineORMAdminBundle\Datagrid\Pager::computeNbResult()`
- `Sonata\DoctrineORMAdminBundle\Datagrid\Pager::getNbResults()`
- `Sonata\DoctrineORMAdminBundle\Datagrid\Pager::setNbResults()`
```

handle SonataAdminBundle Pager::nbresults deprecation

---

src/Datagrid/Pager.php

We may not need to add the countColumn property/methods with the following PR
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1217
```markdown
- Unavoidable deprecation in Pager.
```

Avoid Pager deprecation

---

src/Resources/views/Form/form_admin_fields.html.twig

The user may not have access to delete the object in question, but should be allowed to remove the selection from the list.
The Delete button does not delete the object, so we don't have to check if the user has the ability to delete the object.
```markdown
- Fix for checking if delete button is to be displayed
```

Delete button is independent of the ability to delete an object

---

tests/App/DataFixtures/AuthorFixtures.php
tests/App/DataFixtures/BookFixtures.php
tests/App/DataFixtures/CategoryFixtures.php
tests/App/config/services.php
tests/Functional/CRUDTest.php
tests/Functional/EmbeddedMappingTest.php
tests/Functional/ManyToOneMappingTest.php

This makes easier to add more fixtures and also autowiring and autoconfiguring have been added to fixture files, so there is no need to register new fixture files.

[Tests] Split fixtures into files

---

src/Filter/NumberFilter.php
src/Guesser/FilterTypeGuesser.php
tests/Guesser/FilterTypeGuesserTest.php

`getOptions` is using `array_key_exist` so
```
$this->getOptions('field_type', DateTimeFilter::class)
```
will return `null` instead of `DateTimeFiler::class` when the type is guessed by our guesser.
This issue was reported on slack by someone using the master branch and he tried the fix for me.
```markdown
- Do not provide a default `null` `field_type` option for Filter
```

Do not use null as default value

---

src/Builder/DatagridBuilder.php
src/Datagrid/Pager.php
tests/App/Admin/CarAdmin.php
tests/App/Admin/ItemAdmin.php
tests/App/DataFixtures/CarFixtures.php
tests/App/DataFixtures/CommandFixtures.php
tests/App/DataFixtures/ItemFixtures.php
tests/App/DataFixtures/ProductFixtures.php
tests/App/Entity/Car.php
tests/App/Entity/Command.php
tests/App/Entity/Item.php
tests/App/Entity/Product.php
tests/App/config/services.php
tests/Datagrid/PagerTest.php
tests/Filter/FilterTest.php
tests/Functional/CompositePrimaryKeysTest.php

I added some functional tests for composite primary keys.
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1268/checks?check_run_id=1717007313 show the failure if I removed the code for composite keys.
Then I added the PR https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1217, to check that the code is still working fine.
```markdown
- Use Doctrine ORM Paginator to count in Pager.
- Support of composite key for computeNbResult
```

Add composite primary keys tests and use Paginator

---

src/Admin/FieldDescription.php
src/Block/AuditBlockService.php
src/Builder/DatagridBuilder.php
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php
src/Datagrid/Pager.php
src/DependencyInjection/Compiler/AddAuditEntityCompilerPass.php
src/DependencyInjection/Compiler/AddGuesserCompilerPass.php
src/DependencyInjection/Compiler/AddTemplatesCompilerPass.php
src/DependencyInjection/Configuration.php
src/DependencyInjection/SonataDoctrineORMAdminExtension.php
src/Filter/BooleanFilter.php
src/Filter/CallbackFilter.php
src/Filter/ChoiceFilter.php
src/Filter/ClassFilter.php
src/Filter/DateFilter.php
src/Filter/DateRangeFilter.php
src/Filter/DateTimeFilter.php
src/Model/ModelManager.php
src/SonataDoctrineORMAdminBundle.php
src/Util/ObjectAclManipulator.php
tests/Builder/DatagridBuilderTest.php
tests/Builder/ListBuilderTest.php
tests/Builder/ShowBuilderTest.php
tests/Guesser/FilterTypeGuesserTest.php
tests/Guesser/TypeGuesserTest.php
tests/Model/ModelManagerTest.php

I am targeting this branch, because this breaks BC.
This is part of https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1187
```markdown
- Add final modifier to classes marked as `@final`.
```

close API: make classes final

---

src/Filter/AbstractDateFilter.php
src/Filter/ClassFilter.php
src/Filter/CountFilter.php
src/Filter/NumberFilter.php
src/Filter/StringFilter.php

```markdown
- Passing another `type` value to a filter than an integer handled
```

Deprecate passing a non integer or non existing type

---

src/Datagrid/ProxyQuery.php
src/Exporter/DataSource.php
src/Filter/DateTimeRangeFilter.php
src/Filter/ModelAutocompleteFilter.php
src/Filter/ModelFilter.php
src/Filter/NumberFilter.php
src/Filter/StringFilter.php
src/Filter/TimeFilter.php
src/Guesser/FilterTypeGuesser.php
src/Guesser/TypeGuesser.php
src/Model/AuditReader.php
src/Model/ModelManager.php
tests/Datagrid/ProxyQueryTest.php
tests/Exporter/DataSourceTest.php
tests/Model/ModelManagerTest.php

I am targeting this branch, because this breaks BC.
This is part of https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1187
No Changelog needed I think as its covered by the changelog of https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1295

make remaining classes final

---

src/Filter/ChoiceFilter.php
tests/Filter/ChoiceFilterTest.php
tests/Filter/ModelFilterTest.php

Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1040
I started with ChoiceFilter because it's easier for me. I never used ModelFilter/ModelAutocompleteFilter.
I am targeting this branch, because we can consider this as a patch. But it may need discussions.
```markdown
- `ChoiceFilter` now returns `null` values when used with the type `NOT_EQUAL`
```

Handle null when using NOT_EQUALS with ChoiceFilter

---

src/Builder/DatagridBuilder.php
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php

We're setting `code`, `name` and `label`.
- As explained [here](https://github.com/sonata-project/SonataAdminBundle/pull/6837#discussion_r576771541), I think that removing `code` should be considered as a bugfix. 
- The `name` option is not used.
- The `label` option is useless ; it's already set in the SonataAdminBundle, so the line is doing nothing.
I try it on my project and saw no impact.
```markdown
- Unavoidable deprecation about the `code` option.
```

Remove useless options

---

src/Resources/config/security.xml
src/Util/ObjectAclManipulator.php

ModelManagerInterface->getEntityManager() does not exist.
Similar to https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/blob/3.x/src/Util/ObjectAclManipulator.php
```markdown
- Not passing a `ManagerRegistry` as first argument of `ObjectAclManipulator`
```

Avoid calling a non existant method

---

src/Datagrid/ProxyQueryInterface.php

These methods were removed from `Sonata\AdminBundle\Datagrid\ProxyQueryInterface` in master but are still used in DoctrineORMAdminBundle.

Re-add getUniqueParameterId and entityJoin

---

src/Datagrid/OrderByToSelectWalker.php
src/Datagrid/ProxyQuery.php
src/Datagrid/ProxyQueryInterface.php
src/Exporter/DataSource.php
tests/Datagrid/OrderByToSelectWalkerTest.php
tests/Datagrid/ProxyQueryTest.php
tests/Exporter/DataSourceTest.php

I have a Contract entity and a Client entity.
A client can have multiple contracts. A contract can be associated to multiple clients.
In the `configureQuery` of my `ContractAdmin`, I'm using a `leftJoin('contract.client')`.
I got a weird behavior:
- The total of result was 102.
- I got 4 pages of 32 results (which mean 128 results)
- Some results were missing (in database the query was returning 133 results, but there was no page 5 on the admin)
Distinct is not a good thing to use with pagination:
If the results are:
```
-----------
contract | client
-----------
1 | 1
-----------
2 | 1
-----------
2 | 2
-----------
1 | 2
-----------
3 | 1
-----------
```
With distinct on col 1 and a limit of 2
- Page 1 return contract 1 and 2
- Page 2 return contract 2 and 1
- There is no page 3
With …

Group by is better than distinct

---

src/Builder/DatagridBuilder.php
tests/Builder/DatagridBuilderTest.php

I am targeting this branch, because the issue introduced in master branch.
Setting `field_name` was removed in https://github.com/sonata-project/SonataAdminBundle/pull/6838 and since then SonataAdminBundle relies on the persistence bundle (which SonataDoctrineORMAdminBundle is) to set correct value of this option. Setting of this option was added in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1297/files#diff-f1cf10ef5a385627958c076574e9aefa52d2e24c254e239128812f868aca6808R90 and then was accidentally (I think) removed in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/823c3583553276e1e7dd39c2e94ca87942718ba9#diff-f1cf10ef5a385627958c076574e9aefa52d2e24c254e239128812f868aca6808L87 during resolving conflicts of merging …

Set default field_name value in DatagridBuilder

---

src/Datagrid/ProxyQuery.php

```markdown
- Deprecate passing arguments to `ProxyQuery::execute()` method
```

Deprecate passing arguments to execute method

---

src/Datagrid/ProxyQuery.php

Deprecate passing arguments to `ProxyQuery::execute()`, regardless its values.
Follow up of #1333.

Deprecate passing arguments to `ProxyQuery::execute()`, regardless its values

---

composer.json
tests/Admin/FieldDescriptionTest.php

Address some direct deprecations from tests.

Address some direct deprecations from tests

---

src/DependencyInjection/SonataDoctrineORMAdminExtension.php
src/Filter/EmptyFilter.php

This is an attempt at fixing the failing tests due to reported deprecations by the phpunit bridge.
See conversation [here](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1339#issuecomment-793932725).
Locally for me the issue is fixed by deprecating the Symfony service.
```markdown
- deprecated the `Sonata\DoctrineORMAdminBundle\Filter\EmptyFilter` service since its class is already deprecated since version 3.27
```

mark EmptyFilter service as deprecated

---

src/Block/AuditBlockService.php

No changelog needed, or? The class was final already so this should not impact anyone.
closes https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1187

make AuditBlockService::$auditReader private

---

composer.json
src/Builder/DatagridBuilder.php
src/Builder/FormContractor.php
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php
src/FieldDescription/FieldDescriptionFactory.php
src/Guesser/AbstractTypeGuesser.php
src/Guesser/FilterTypeGuesser.php
src/Guesser/TypeGuesser.php
src/Model/ModelManager.php
src/Resources/config/doctrine_orm.xml
tests/Builder/DatagridBuilderTest.php
tests/Builder/ListBuilderTest.php
tests/Builder/ShowBuilderTest.php
tests/Guesser/FilterTypeGuesserTest.php
tests/Guesser/TypeGuesserTest.php
tests/Model/ModelManagerTest.php

Closes #1348.
Closes #1296.
```markdown
- Added `FieldDescriptionFactory` class
- `AbstractTypeGuesser` class
- `FilterTypeGuesser::guessType()`
- `TypeGuesser::guessType()`
- `ModelManager:: getParentMetadataForProperty()`
- `ModelManager:: getNewFieldDescriptionInstance()`
- `ModelManager:: getModelInstance()`
```

Add FieldDescriptionFactory

---

src/Model/AuditReader.php
tests/Model/AuditReaderTest.php

I am targeting this branch, because BC-break.
Closes #1085.

AuditReader::find and AuditReader::findRevision should not throw exception and return null instead

---

src/Datagrid/Pager.php
src/Exporter/DataSource.php
src/Filter/AbstractDateFilter.php
src/Filter/Filter.php
src/Filter/ModelAutocompleteFilter.php
src/Filter/ModelFilter.php
src/Filter/StringFilter.php

Fix missing argument 2 for `trigger_error()`.
```markdown
- Missing argument 2 in calls to `trigger_error()`.
```

Fix missing argument 2 for `trigger_error()`

---

tests/Filter/BooleanFilterTest.php
tests/Filter/CallbackFilterTest.php
tests/Filter/ChoiceFilterTest.php
tests/Filter/ClassFilterTest.php
tests/Filter/CountFilterTest.php
tests/Filter/DateFilterTest.php
tests/Filter/DateRangeFilterTest.php
tests/Filter/DateTimeFilterTest.php
tests/Filter/DateTimeRangeFilterTest.php
tests/Filter/EmptyFilterTest.php
tests/Filter/FilterTestCase.php
tests/Filter/ModelFilterTest.php
tests/Filter/NullFilterTest.php
tests/Filter/NumberFilterTest.php
tests/Filter/StringFilterTest.php
tests/Filter/StringListFilterTest.php
tests/Filter/TimeFilterTest.php

This provide a way to fix phpstan error with filters in test directory, because `query` and `queryParameters` doesn't exist on both `ProxyQuery` and `QueryBuilder`.

Fix phpstan issue with tests

---

src/Filter/Filter.php
tests/Filter/FilterTest.php

Fix filter query when using "OR" conditions.
Rework of #925, keeping BC.
Fixes sonata-project/SonataAdminBundle#2850.
Fixes sonata-project/SonataAdminBundle#3368.
Fixes sonata-project/SonataAdminBundle#5569.
```markdown
- Resulting `WHERE` clause from `Filter::applyWhere()` when using `OR` conditions on queries that already have previous conditions.
```

Fix filter query when using "OR" conditions

---

src/Resources/config/audit.xml
tests/Admin/FieldDescriptionTest.php
tests/Fixtures/Entity/AssociatedEntity.php
tests/Model/ModelManagerTest.php

Adds the tag introduced in https://github.com/sonata-project/SonataAdminBundle/pull/6983 to the audit reader.
I am targeting this branch, because these changes are BC.
```markdown
- Fixed triggering deprecation because audit reader is not tagged.
```

Tag AuditReader

---

src/Datagrid/ProxyQuery.php

I am targeting this branch, because these changes are pedantic.

Remove extra argument separator in `sprintf()` calls at `ProxyQuery`

---

.github/workflows/test-platforms.yaml
tests/App/config/config.yml

This is just copy-pasting the job we have and execute it for `MySQL` and `Postgres`. I created another file so I guess there is no need to modify `dev-kit`. 
We could maybe test just with one variant and do not test lower versions.
Ref: https://github.com/sonata-project/dev-kit/issues/1477

Test on different platforms

---

src/Model/ModelManager.php

This deprecation was always triggered from `sonata-project/admin-bundle`, ref: https://github.com/sonata-project/SonataAdminBundle/pull/7002
I am targeting this branch, because this change is BC.
```markdown
- Fixed triggering always deprecation when calling `ModelManager::getDefaultSortValues()` method
```

Avoid always triggering deprecation

---

tests/App/Admin/SubAdmin.php
tests/App/Entity/Sub.php

Tests failed [when merging with `master`](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1400) because `SubAdmin` is listing `$list->add('otherField');` and `otherField` is private.
In `3.x` it shows a blank space, but in `4.x` will throw an exception, in tests it showed:
```
32x: Accessing a non existing value for the field "otherField" is deprecated since sonata-project/admin-bundle 3.67 and will throw an exception in 4.0.
32x in EntityInheritanceTest::testList from Sonata\DoctrineORMAdminBundle\Tests\Functional
```

Make property public

---

UPGRADE-3.x.md
composer.json
docs/reference/filter_field_definition.rst
src/Filter/StringFilter.php
src/Resources/config/doctrine_orm_filter_types.xml
tests/Filter/FilterTest.php
tests/Filter/StringFilterTest.php

Use "BINARY()" DQL function for case sensitive MySQL pattern matching in `StringFilter::filter()`.
Closes #1387.
```markdown
- Call to `BINARY()` (`DoctrineExtensions\Query\Mysql\Binary`) DQL function for MySQL pattern matching when it is available and "case_sensitive" option is set to `true` in `StringFilter::filter()`.
- Default value for the "case_sensitive" option from `true` to `null` in `StringFilter`.
- Respecting "case_sensitive" when it is set to `true` along MySQL columns using other collations than "utf8mb4_0900_as_cs" or "utf8mb4_bin".
- Omitting or not passing an instance of `Doctrine\ORM\EntityManagerInterface` as argument 1 to `StringFilter::__construct()`.
```

Use "BINARY()" DQL function for case sensitive MySQL pattern matching in `StringFilter::filter()`

---

composer.json
phpstan-baseline.neon
phpstan.neon.dist
src/Block/AuditBlockService.php
src/Builder/DatagridBuilder.php
src/Builder/ListBuilder.php
src/Builder/ShowBuilder.php
src/Datagrid/Pager.php
src/Datagrid/ProxyQuery.php
src/DependencyInjection/Compiler/AddAuditEntityCompilerPass.php
src/DependencyInjection/Compiler/AddTemplatesCompilerPass.php
src/DependencyInjection/SonataDoctrineORMAdminExtension.php
src/FieldDescription/FieldDescriptionFactory.php
src/Filter/ChoiceFilter.php
src/Filter/Filter.php
src/Model/ModelManager.php
tests/App/DataFixtures/BookFixtures.php
tests/App/DataFixtures/ItemFixtures.php
tests/App/Entity/Author.php
tests/Block/AuditBlockServiceTest.php
tests/Filter/ClassFilterTest.php
tests/Filter/CountFilterTest.php
tests/Filter/NumberFilterTest.php
tests/Functional/CRUDTest.php
tests/Functional/EmbeddedMappingTest.php
tests/Functional/ManyToOneMappingTest.php

Need
- https://github.com/doctrine/persistence/pull/163
- https://github.com/sonata-project/EntityAuditBundle/pull/382
- https://github.com/doctrine/orm/pull/8590

Raise phpstan to max level

---

tests/Block/AuditBlockServiceTest.php

It fails because of https://github.com/sonata-project/EntityAuditBundle/pull/382, this PR fixes the fail, but I guess we introduced a BC break adding those type declarations.

Fix Revision instantiation

---

src/Model/ModelManager.php

Fix return type for `ModelManager::getModelIdentifier()`.
I am targeting this branch, because these changes are fixing what the [`ModelManagerInterface`](https://github.com/sonata-project/SonataAdminBundle/blob/627e79d2dd24bf77ffd3f33865b7dab007199389/src/Model/ModelManagerInterface.php#L136-L149) declares.
Additionally, the character "," was replaced with `ModelManager::ID_SEPARATOR` in the call to `implode()`, as that seems to be the proper character if you see other methods:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/6238cbe02103edb66b3a02750920405626fbd5a1/src/Model/ModelManager.php#L333
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/6238cbe02103edb66b3a02750920405626fbd5a1/src/Model/ModelManager.php#L521 …

Fix return type for `ModelManager::getModelIdentifier()`

---

composer.json

It also updates the conflict section removing `sonata-project/core-bundle` and updating `sonata-project/block-bundle` to the version required in `require-dev` section.

Add stability alpha to sonata-project/admin-bundle

---

UPGRADE-3.x.md
composer.json
docs/reference/filter_field_definition.rst
src/Filter/StringFilter.php
src/Resources/config/doctrine_orm_filter_types.xml
tests/Filter/FilterTest.php
tests/Filter/StringFilterTest.php

Introduce "force_case_insensitivity" option and deprecate "case_sensitive" in `StringFilter`.
Closes #1415.
Reverts #1395.
```markdown
- "force_case_insensitivity" option to `StringFilter` in order to force the database to ignore the case sensitivity when matching filters.
- "case_sensitive" option in `StringFilter`.
```

Introduce "force_case_insensitivity" option and deprecate "case_sensitive" in `StringFilter`

---

docs/index.rst
docs/reference/data_source.rst

Documentation on how to set the date time format for exported data.
As suggested here: https://github.com/sonata-project/SonataAdminBundle/issues/7105#issuecomment-824754776

documentation for custom DataSource

---

composer.json
src/DependencyInjection/Compiler/AddAuditEntityCompilerPass.php
src/DependencyInjection/Compiler/AddGuesserCompilerPass.php
src/DependencyInjection/Compiler/AddTemplatesCompilerPass.php
src/DependencyInjection/Configuration.php
src/SonataDoctrineORMAdminBundle.php
tests/DependencyInjection/Compiler/AddTemplatesCompilerPassTest.php

```markdown
- `templates.form` and `templates.filter` config
- Always merge `SonataDoctrineORMAdmin` form and filter templates.
- Using `sonata_admin` configuration.
```

Stop using SonataAdmin config in doctrineORMAdmin

---

UPGRADE-3.x.md
src/Filter/CallbackFilter.php
tests/Filter/CallbackFilterTest.php
tests/Fixtures/Util/CallbackClass.php

`FilterData` will be introduced in version 4.0 as type declaration of argument 4 of `Filter::apply()`.
This adds an upgrade path when using `CallbackFilter` which receives a `callable` instance in order to filter.
If this `callable` does not use a type declaration for argument 4 or uses `array` (current type), it triggers a deprecation.
I am targeting this branch, because these changes are BC.
```markdown
- Deprecated not adding `FilterData` as type declaration of argument 4 in the callable passed to `CallbackFilter`
```

Add forward compatibility with FilterData

---

src/Datagrid/Pager.php
src/Datagrid/ProxyQuery.php
tests/App/Admin/AuthorAdmin.php
tests/App/Admin/AuthorWithSimplePagerAdmin.php
tests/App/config/services.php
tests/Datagrid/ProxyQueryTest.php
tests/Functional/SimplePagerTest.php

I am targeting this branch, because bugfix.
It could technically be considered as a BC-break since `execute` method is now returning a `Paginator` instead of an `array`. But the phpdoc were saying `mixed` so I don't think there is a real BC-promise about the returning value.
It's still Countable and Traversable, and this is the only solution I found.
Closes #1403.
```markdown
- `ProxyQuery::execute()` is now returning a Paginator instead of an array.
- Support for fetch join with simple pager.
```

Try to fix Simple pager

---

src/Filter/Filter.php
tests/App/Admin/BookWithAuthorAutocompleteAdmin.php
tests/App/config/services.php
tests/Filter/FilterTest.php
tests/Functional/RetrieveAutocompleteItemsActionTest.php

Fix binding arbitrary params as part of a value expression in the query filter at `Filter::applyWhere()` with PostgreSQL.
Closes #1389.
```markdown
- Bind arbitrary params as part of a value expression in the query filter at `Filter::applyWhere()` with PostgreSQL.
```

Fix binding arbitrary params as part of a value expression in the query filter at `Filter::applyWhere()` with PostgreSQL

---

src/Filter/Filter.php
tests/App/DataFixtures/AuthorFixtures.php
tests/Filter/FilterTest.php
tests/Functional/RetrieveAutocompleteItemsActionTest.php

Fix "OR" condition used as marker at `Filter::addOrParameter()`.
The assertion in this clause must be false.
Changelog is not required since the fixed issue is not released yet.
Closes #1446.

Fix "OR" condition used as marker at `Filter::addOrParameter()`

---

src/Exporter/DataSource.php
tests/Exporter/DataSourceTest.php

Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1360#issuecomment-854648936
```markdown
- Export for admin with fetch join in the `configureQuery()` method.
```

Fix dataSource when fetch join are used

---

tests/Datagrid/OrderByToSelectWalkerTest.php
tests/Datagrid/PagerTest.php
tests/Datagrid/ProxyQueryTest.php
tests/Fixtures/TestEntityManagerFactory.php
tests/Util/SmartPaginatorFactoryTest.php

Closes https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1460
I investigated a bit. Mocking the EntityManager seems not doable easily for those tests. So took the functionality from `DoctrineTestHelper` and reduced it to a minimum for what we need.
Technically we only need this on master... but I thought it can't hurt to do it on 3.x already?

remove usages of deprecated DoctrineTestHelper

---

docs/reference/filter_field_definition.rst
src/Builder/DatagridBuilder.php
src/Filter/StringFilter.php
tests/Filter/StringFilterTest.php

BC
```markdown
- `global_search` option to the `StringFilter`
- Stop using `ChoiceTypeFilter` for global search 
```

Implement SearchableFilterInterface

---

docs/reference/filter_field_definition.rst
src/Filter/EmptyFilter.php
tests/Filter/EmptyFilterTest.php

I am targeting this branch, because there is already an empty filter in 3.x.
Closes #1437.
```markdown
- `EmptyFilter`
```

Add Empty filter

---

src/Datagrid/Pager.php
tests/Datagrid/PagerTest.php

See https://github.com/sonata-project/SonataAdminBundle/issues/7328
```markdown
`Pager::getCurrentPageResults()` does not return `Paginator` anymore.
```

Avoid duplicate query with current page results

---

src/Filter/Filter.php
src/Filter/GroupableConditionAwareInterface.php
tests/Filter/FilterTest.php

Add `GroupableConditionAwareInterface`.
I tried to finish the PR #1466
```markdown
- `GroupableConditionAwareInterface`.
- "or_group" option in `Filter` objects;
- `Filter::$groupedOrExpressions`.
- Not resetting `Filter::$groupedOrExpressions` static property (see sonata-project/SonataAdminBundle#7096).
```

Add `GroupableConditionAwareInterface`

---

docs/reference/data_source.rst

added arguments key, as it is required since 4.0-rc.2
Fixed custom exporter DataSource service definition

Fixed custom exporter DataSource service definition

---

composer.json
src/FieldDescription/FieldDescriptionFactory.php
tests/FieldDescription/FieldDescriptionTest.php

Rely on AdminBundle
I am targeting this branch, because BC-break.
```markdown
- Do not set a default route option to `FieldDescription` in `FieldDescriptionFactory`
```

Remove default route in this bundle
