Builder/DatagridBuilder.php
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | -
| SonataAdminBundle PR        | sonata-project/SonataAdminBundle#2656
=> Added support for SimplePager

Resources/views/CRUD/list_orm_one_to_many.html.twig
@rande this PR fix the issue #418 
I tested it.
Thanks
=> fix Not showing link in sonata admin on relational one_to_many

Filter/AbstractDateFilter.php, Filter/DateFilter.php, Filter/DateRangeFilter.php, Filter/DateTimeFilter.php, Filter/DateTimeRangeFilter.php, Filter/TimeFilter.php
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | -
=> Fix wrong field type on DateFilter, DateTimeFilter and DateRangeFilter.

Builder/DatagridBuilder.php, Filter/ModelAutocompleteFilter.php, Resources/config/doctrine_orm_filter_types.xml, Resources/doc/reference/filter_field_definition.rst
| Bug fix?      | no
| New feature?  | yes
| Fixed tickets | sonata-project/SonataAdminBundle#2360
| SonataAdmin PR        | sonata-project/SonataAdminBundle#2454
=> Added model autocomplete filter: doctrine_orm_model_autocomplete

Resources/views/CRUD/edit_orm_many_association_script.html.twig
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | #404
=> Removed code that breaks selecting items in sonata_type_model_list (version 2.3)

Resources/views/Block/block_audit.html.twig, Resources/views/CRUD/edit_orm_many_to_many.html.twig, Resources/views/CRUD/edit_orm_many_to_one.html.twig, Resources/views/CRUD/edit_orm_one_to_many.html.twig, Resources/views/CRUD/edit_orm_one_to_one.html.twig, Resources/views/Form/form_admin_fields.html.twig
PR linked to https://github.com/sonata-project/SonataAdminBundle/pull/2754
=> Admin LTE 2.0

Resources/views/Form/form_admin_fields.html.twig
Requires https://github.com/sonata-project/SonataAdminBundle/pull/3026
=> Fixed sonata_help to be displayed on sonata_type_model_list

Resources/views/CRUD/list_orm_many_to_many.html.twig, Resources/views/CRUD/list_orm_many_to_one.html.twig, Resources/views/CRUD/list_orm_one_to_many.html.twig, Resources/views/CRUD/list_orm_one_to_one.html.twig, Resources/views/CRUD/show_orm_many_to_many.html.twig, Resources/views/CRUD/show_orm_many_to_one.html.twig, Resources/views/CRUD/show_orm_one_to_many.html.twig, Resources/views/CRUD/show_orm_one_to_one.html.twig
=> Fix wrong association route checks

Filter/AbstractDateFilter.php
This PR takes code from issues #346, #345, #285 from original authors: @cassianotartari, @sirian. I fixed some minor issues and added into this PR so it can be merged into current code without conflicts.
| Bug fix?      | yes
| New feature?  | no
| Fixed tickets | #346, #345, #285
=> Date filter should filter records for the whole day

Model/ModelManager.php, Tests/Fixtures/Entity/VersionedEntity.php, Tests/Model/ModelManagerTest.php
Needs https://github.com/sonata-project/SonataAdminBundle/pull/3170
ModelManager now implements the LockInterface.
=> Add version lock

Block/AuditBlockService.php
=> Fix deprecated settings method on block service

Resources/views/CRUD/edit_orm_many_to_one.html.twig, Resources/views/CRUD/edit_orm_one_to_one.html.twig
Do not show `<span class="btn-group">` if all action buttons disabled
=> Remove empty space after ManyToOne and OneToOne

Resources/views/CRUD/edit_orm_one_to_many.html.twig
Added sortable feature from the table view to the standard form view.
=> Allow sortable for standard form view

Resources/views/CRUD/edit_orm_one_to_many.html.twig
=> Use translation_domain on collection labels

Filter/BooleanFilter.php, Filter/ChoiceFilter.php
Boolean filter should be rendered as choice with yes/no options. Currently it renders like text input.
=> Fix rendering of boolean filter and remove unused private method.

composer.json
**THIS BUNDLE WILL BE HAVE NEW MAJOR RELEASE**
* 3.x-dev
* Use new composer constraints notation
=> Composer fixes and improves

composer.json
As the issue come only on Travis, this is not necessary to add this on the require section.
Ref: #557
=> Move knplabs/knp-menu-bundle to require-dev

composer.json
The build was failing, due to a new composer lint check
https://travis-ci.org/sonata-project/SonataDoctrineORMAdminBundle/jobs/134351567
=> use new valid composer syntax

Resources/views/CRUD/edit_orm_one_to_many.html.twig, Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig, Resources/views/CRUD/edit_orm_one_to_many_inline_tabs.html.twig, Resources/views/CRUD/edit_orm_one_to_many_sortable_script_table.html.twig, Resources/views/CRUD/edit_orm_one_to_many_sortable_script_tabs.html.twig
I am targetting this branch, because this is just whitespace
Not even sure one can see some of this lines in their entirety on a 4K
display.
=> Avoid long lines

Model/ModelManager.php
=> Entity state code improvement

Guesser/FilterTypeGuesser.php, phpunit.xml.dist
I am targeting this branch, because this is pedantic.
I think coverage is not calculated correctly, lets see
=> Remove exceptions from phpunit whitelist

Resources/views/CRUD/list_orm_one_to_many.html.twig
=> added missing whitespace

Datagrid/ProxyQuery.php, Tests/Datagrid/ProxyQueryTest.php
=> Merge stable

composer.json
The test suite says it is compatible.
```markdown
- It is now allowed to install Symfony 4
```
=> Allow upgrading to sf4

src/Datagrid/ProxyQuery.php, tests/Admin/FieldDescriptionTest.php, tests/Builder/DatagridBuilderTest.php, tests/Builder/FormContractorTest.php, tests/Builder/ListBuilderTest.php, tests/Datagrid/ProxyQueryTest.php, tests/DependencyInjection/Compiler/AddAuditEntityCompilerPassTest.php, tests/DependencyInjection/Compiler/AddTemplatesCompilerPassTest.php, tests/Filter/ModelFilterTest.php, tests/Guesser/FilterTypeGuesserTest.php, tests/Model/ModelManagerTest.php
=> Manual merge

tests/Block/AuditBlockServiceTest.php, tests/Builder/DatagridBuilderTest.php, tests/Builder/ListBuilderTest.php, tests/Builder/ShowBuilderTest.php, tests/DependencyInjection/Compiler/AddGuesserCompilerPassTest.php, tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php, tests/Filter/ClassFilterTest.php, tests/Filter/DateTimeFilterTest.php, tests/Filter/DateTimeRangeFilterTest.php, tests/Filter/TimeFilterTest.php, tests/Fixtures/Entity/AbstractEntity.php, tests/Guesser/TypeGuesserTest.php, tests/Model/AuditReaderTest.php, tests/Model/ModelManagerTest.php, tests/SonataDoctrineORMAdminBundleTest.php
Adding tests that are missing, as much as I can.
=> Add missing tests

docs/reference/filter_field_definition.rst
Ref https://github.com/sonata-project/SonataAdminBundle/issues/1891
Fixed a typo inside the filter field list definition
=> Fixed a typo on doctrine_orm_number

src/Datagrid/Pager.php, tests/Datagrid/PagerTest.php
Closes #834
```markdown
- Composite key not working
```
Basically, I tried to preserve the feature from #827 but still revert to the old way.
=> Revert support for composite key

docs/reference/filter_field_definition.rst
I am targeting this branch, because i made a minor fix in documentation 
Based on issue : https://github.com/sonata-project/SonataAdminBundle/issues/4903#issuecomment-383885345
=> Correct checkbox Class call documentation

composer.json, src/Model/ModelManager.php
```markdown
- Compatibility with `sonata-project/exporter` 2
```
=> Allow exporter 2

docs/reference/list_field_definition.rst, docs/reference/query_proxy.rst, docs/reference/templates.rst, docs/tutorial/creating_your_first_admin_class/defining_admin_class.rst, docs/tutorial/creating_your_first_admin_class/defining_entities.rst
Refs https://github.com/sonata-project/SonataAdminBundle/pull/5508
=> different fixes to be consistent

src/Resources/views/Form/form_admin_fields.html.twig
```markdown
- Don't hide edit button `sonata_type_model_list_widget` if there is no value
```
=> Don't hide edit button if there is no value

src/Filter/AbstractDateFilter.php, src/Filter/ClassFilter.php, src/Filter/NumberFilter.php, src/Filter/StringFilter.php
I am targeting this branch, because I expose a new constant
Closes #920
```markdown
Create const for operator choices in Filter classes
```
=> Expose const for Operator choices in filter classes

composer.json, src/Model/ModelManager.php, tests/Model/ModelManagerTest.php
I am targeting this branch, because this is not be a BC break?
Closes #947 
```markdown
- Added support for Doctrine-Bundle 2.0
```
=> allow DoctrineBundle 2.0

src/Builder/DatagridBuilder.php
Datagrid filters form data is passed as array, so it is validated with the Valid constraint (see https://symfony.com/doc/3.4/form/without_class.html#adding-validation).
Some errors related to linked objets, but unrelated to the form, can then appear in the filters block.
On a child admin datagrid, the parent id is stored in a hidden field. The parent object is validated while building the form and if it has a Callback validator, errors might be displayed in the filters block.
I am targeting this branch, because it's a patch without backward compatibility changes.
```markdown
Disabled validation group in Builder/DatagridBuilder::getBaseDatagrid
```
=> Disable validation groups on datagrid filter form

.travis.yml, composer.json, tests/Builder/ShowBuilderTest.php, tests/Guesser/TypeGuesserTest.php, tests/Model/AuditReaderTest.php
I am targeting this branch, because this does not contain BC break
```markdown
- Bump SF to 4.4
```
=> Bump to SF 4.4

tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php
Ref: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/992
=> Fix missing prepending extension

tests/Filter/BooleanFilterTest.php, tests/Filter/ChoiceFilterTest.php, tests/Filter/ModelFilterTest.php, tests/Filter/QueryBuilder.php, tests/Filter/StringFilterTest.php
#Subject 
The mock of the QueryBuilder was kinda weird
No changelog for tests
=> Make notIn and In function consistent

tests/DependencyInjection/SonataDoctrineORMAdminExtensionTest.php
First https://github.com/sonata-project/SonataAdminBundle/pull/5981 has be merged
=> Revert "Fix missing prepending extension"

src/Filter/AbstractDateFilter.php
```markdown
- Removed deprecated usage of Admin FormType constants
```
=> Fix deprecation

composer.json
I am targeting this branch, because it's BC,  but I'll need to fix a PR made in master.
The PR https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1004 need sonata 3.62 at least, but 3.62 has some issue with intl so I require 3.63
Not needed in this case ?
=> Update admin version

src/Datagrid/ProxyQuery.php
What do you think about adding `@method` for IDE ?
```markdown
- `@method` Annotation for ProxyQuery
```
=> Add method annotation for ProxyQuery

src/Block/AuditBlockService.php
=> Improve deprecation messages for AuditBlockService

src/Guesser/AbstractTypeGuesser.php, tests/Admin/FieldDescriptionTest.php, tests/Builder/ShowBuilderTest.php
I am targeting this branch, because pedantic.
=> Pedantic improvements

src/Guesser/AbstractTypeGuesser.php, tests/Admin/FieldDescriptionTest.php, tests/Builder/ShowBuilderTest.php
I need this for https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1073
=> Merge 3.x into Master

src/Builder/FormContractor.php
No need for a changelog since it's not release yet.
Fix: https://github.com/sonata-project/SonataMediaBundle/issues/1766
=> Fix signature

CHANGELOG.md, UPGRADE-3.x.md, src/Block/AuditBlockService.php, src/Filter/StringFilter.php, tests/Block/DeprecatedAuditBlockServiceTest.php, tests/Filter/StringFilterTest.php
=> Prepare release 3.21

tests/Block/AuditBlockServiceTest.php, tests/Block/DeprecatedAuditBlockServiceTest.php
=> Fix block related tests

composer.json
Add support for Twig 3
```markdown
- Add support for Twig 3
```
=> Add support for Twig 3

composer.json
The necessary changes to be compatible were made in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/966
I am targeting this branch, because these changes are BC.
```markdown
- Allow `doctrine/persistence` 2.
```
=> Allow doctrine/persistence 2

composer.json
Similar to https://github.com/sonata-project/SonataAdminBundle/pull/6395
=> Update keywords of composer.json

src/Builder/FormContractor.php, src/Guesser/FilterTypeGuesser.php, src/Guesser/TypeGuesser.php, tests/Guesser/FilterTypeGuesserTest.php
I am targeting this branch, because we need it to be compatible with SonataAdminBundle 4.
```markdown
- compatibility with SonataAdminBundle 4
```
=> fix compatibility with SonataAdminBundle 4

tests/Block/AuditBlockServiceTest.php
=> Remove useless anotation legacy

composer.json
Pedantic
I'm not sure, but it seems like it was installed but not used ?
=> Use correctly phpstan-symfony

src/Datagrid/ProxyQuery.php, src/Datagrid/ProxyQueryInterface.php
Then I'll replace every magic `foo` call by `getQueryBuilder->foo()`
Closes #1216.
```markdown
- Added `Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQueryInterface`
```
=> Introduce DoctrineORMProxyQueryInterface

docs/reference/filter_field_definition.rst
=> Fix param name in doc

src/Resources/views/CRUD/edit_orm_many_to_many.html.twig, src/Resources/views/CRUD/edit_orm_many_to_one.html.twig, src/Resources/views/CRUD/edit_orm_one_to_many.html.twig, src/Resources/views/CRUD/edit_orm_one_to_one.html.twig, src/Resources/views/Form/form_admin_fields.html.twig
```markdown
- Changing access checking in views (isGranted to hasAccess)
```
=> Changing access checking in views (isGranted to hasAccess)

composer.json, src/Datagrid/Pager.php
```markdown
- Added Pager::getCurrentPageResults()
- Deprecated Pager::getResults()
```
=> Add getCurrentPageResults

src/Resources/views/Block/block_audit.html.twig, src/Resources/views/CRUD/edit_orm_many_to_many.html.twig, src/Resources/views/CRUD/edit_orm_many_to_one.html.twig, src/Resources/views/CRUD/edit_orm_one_to_many.html.twig, src/Resources/views/CRUD/edit_orm_one_to_many_inline_tabs.html.twig, src/Resources/views/CRUD/edit_orm_one_to_one.html.twig, src/Resources/views/CRUD/list_orm_many_to_one.html.twig, src/Resources/views/CRUD/list_orm_one_to_one.html.twig, src/Resources/views/CRUD/show_orm_many_to_many.html.twig, src/Resources/views/CRUD/show_orm_many_to_one.html.twig, src/Resources/views/CRUD/show_orm_one_to_many.html.twig, src/Resources/views/CRUD/show_orm_one_to_one.html.twig, src/Resources/views/Form/form_admin_fields.html.twig
I am targeting this branch, because no bc-break.
```markdown
Code formatting in views and change from `<a>` with empty href to button.
```
=> Code formatting in views

composer.json
This fixes tests failing in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1270
=> Bump symfony/panther to 0.9

src/Datagrid/Pager.php
Shall we do cleanup like this already on master?
=> remove deprecated code & cleanup Pager

src/Guesser/TypeGuesser.php, tests/Builder/ShowBuilderTest.php
=> Stop using deprecated constants

src/Builder/FormContractor.php, src/Builder/ListBuilder.php, src/Builder/ShowBuilder.php, src/Guesser/TypeGuesser.php, tests/Builder/FormContractorTest.php, tests/Builder/ListBuilderTest.php, tests/Builder/ShowBuilderTest.php, tests/Guesser/TypeGuesserTest.php
This is a start to clean-up `NEXT_MAJOR` comments on master.
I am targeting this branch, because we need to prepare master for releasing 4.0.
=> cleanup some NEXT_MAJOR comments

src/Filter/CountFilter.php, tests/Filter/BooleanFilterTest.php, tests/Filter/CallbackFilterTest.php, tests/Filter/ChoiceFilterTest.php, tests/Filter/ClassFilterTest.php, tests/Filter/CountFilterTest.php, tests/Filter/DateRangeFilterTest.php, tests/Filter/EmptyFilterTest.php, tests/Filter/FilterTestCase.php, tests/Filter/ModelFilterTest.php, tests/Filter/NullFilterTest.php, tests/Filter/NumberFilterTest.php, tests/Filter/StringFilterTest.php, tests/Filter/StringListFilterTest.php
I am targeting this branch, because bugfix.
cc @rgrassian 
```markdown
- Fixed `CountFilter`
```
=> Fix countFilter condition

src/Admin/FieldDescription.php, src/Builder/DatagridBuilder.php, tests/Admin/FieldDescriptionTest.php, tests/Builder/DatagridBuilderTest.php
Need a PR on SonataAdmin first: https://github.com/sonata-project/SonataAdminBundle/pull/6838
=> Remove NEXT_MAJOR comment for DatagridBuilder

src/Builder/DatagridBuilder.php
Related to https://github.com/sonata-project/SonataAdminBundle/pull/6828
=> Add next major comment

tests/Admin/FieldDescriptionTest.php
See https://github.com/sonata-project/SonataAdminBundle/commit/271e4ed5100e80ef1365c5be639a96b94ab1f302#diff-c698cbb1f2afce655c27e32ebfc8d9f37af04b8164a1d8d609da71d2858c6697R39
=> fix compatiblity with latest SonataAdminBundle changes

src/Builder/DatagridBuilder.php, src/Filter/AbstractDateFilter.php, src/Filter/CallbackFilter.php, src/Filter/ClassFilter.php, src/Filter/CountFilter.php, src/Filter/NumberFilter.php, src/Filter/StringFilter.php, src/Model/ModelManager.php, tests/Filter/CallbackFilterTest.php, tests/Filter/StringFilterTest.php, tests/Model/ModelManagerTest.php
Removed all `NEXT_MAJOR` comments
=> remove NEXT_MAJOR comments

.github/workflows/test.yaml, composer.json
```markdown
- Added support for PHP 8.0
```
=> Allow php 8.0

src/Filter/Filter.php, src/Model/ModelManager.php, src/Resources/config/security.xml, src/Util/ObjectAclManipulator.php, tests/Model/ModelManagerTest.php
We're accessing public property of ClassMetadataInfo, so this cannot be a ClassMetadataInterface.
=> Prepare Phpstan level 2

src/Filter/Filter.php
Same than https://github.com/sonata-project/SonataAdminBundle/pull/6907
=> Allow null type

src/Builder/FormContractor.php, src/Model/ModelManager.php, tests/Builder/FormContractorTest.php
=> Fix some static analysis errors

UPGRADE-3.x.md, composer.json, src/Model/ModelManager.php, tests/Model/ModelManagerTest.php
```markdown
- `ModelManager::reverseTransform()`
- `ModelManager::modelReverseTransform()`
```
=> Add reverseTransform

src/Builder/DatagridBuilder.php, src/Builder/FormContractor.php, src/Builder/ListBuilder.php, src/Builder/ShowBuilder.php, tests/Builder/DatagridBuilderTest.php, tests/Builder/FormContractorTest.php, tests/Builder/ListBuilderTest.php, tests/Builder/ShowBuilderTest.php
Compatibility with https://github.com/sonata-project/SonataAdminBundle/pull/6952
=> Remove admin from signature

src/Datagrid/Pager.php, src/Datagrid/ProxyQuery.php, tests/App/Admin/AuthorAdmin.php, tests/App/DataFixtures/AuthorFixtures.php, tests/App/DataFixtures/BookFixtures.php, tests/App/Entity/Author.php, tests/App/Entity/Book.php, tests/App/Entity/Reader.php, tests/App/config/services.php, tests/App/templates/author/list_number_of_books_field.html.twig, tests/App/templates/author/list_number_of_readers_field.html.twig, tests/App/templates/author/list_outer_list_rows_list.html.twig, tests/Functional/EmbeddedMappingTest.php, tests/Functional/FetchJoinListTest.php, tests/Functional/ManyToOneMappingTest.php
I am targeting this branch, because bugfix.
Closes #1360.
Closes #1361.
```markdown
- Fetch join queries for Pager
- Pager when using entity inheritance
```
=> Use Paginator to display results

UPGRADE-3.x.md, src/Builder/ListBuilder.php, src/Datagrid/ProxyQuery.php, src/DependencyInjection/SonataDoctrineORMAdminExtension.php, src/Guesser/AbstractTypeGuesser.php, src/Guesser/FilterTypeGuesser.php, src/Guesser/TypeGuesser.php, src/Model/ModelManager.php
I'm waiting for https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1373 to release, but I'm preparing the 3.x deprecations messages since I'll do the merge 3.x into master
=> Prepare 3.32

src/Filter/Filter.php, tests/Filter/FilterTest.php
Rename filter option "admin_code" to "or_group".
I am targeting this branch, because the change here has no release yet.
Related to https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1358#pullrequestreview-622845074.
The tests were also improved.
=> Rename filter option "admin_code" to "or_group"

src/Resources/config/doctrine_orm_filter_types.xml
Closes #1392
```markdown
- Added missing filter declaration in the config
```
=> Add missing filter declaration

src/Resources/config/doctrine_orm_filter_types.xml
Pedantic since it's not release
=> Fix declaration of filters

composer.json, tests/App/Admin/AuthorAdmin.php, tests/App/Admin/BookAdmin.php, tests/App/Admin/CarAdmin.php, tests/App/Admin/CategoryAdmin.php, tests/App/Admin/ItemAdmin.php, tests/App/Admin/SubAdmin.php, tests/App/DataFixtures/SubFixtures.php, tests/App/Entity/Base.php, tests/App/Entity/Sub.php, tests/App/config/services.php, tests/Functional/BaseFunctionalTestCase.php, tests/Functional/CRUDTest.php, tests/Functional/DatagridTest.php, tests/Functional/EntityInheritanceTest.php
Closes https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1370
It is based on https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/1361
=> Add inheritance test

composer.json
I am targeting this branch, because this is the one.
```markdown
- Add compatiblity with all SonataAdmin 4.0 versions
```
=> Do not restrict to alpha-1

src/Model/ModelManager.php, src/Util/ObjectAclManipulator.php
=> Fix batchDelete

docs/reference/filter_field_definition.rst, docs/reference/form_field_definition.rst, docs/reference/form_types_and_transformers.rst, docs/reference/list_field_definition.rst, docs/reference/templates.rst
=> Update doc to the last developement

src/Builder/DatagridBuilder.php
A comment was added in 3.x
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Builder/DatagridBuilder.php#L188
=> Resolve NEXT_MAJOR

composer.json, src/Resources/config/doctrine_orm.xml
Needed for https://github.com/sonata-project/SonataAdminBundle/pull/7301
```markdown
- Deprecation from SonataAdminBundle 3.x
```
=> Add FormRegistry argument for FormContractor

src/Builder/DatagridBuilder.php, src/Builder/ListBuilder.php, src/Builder/ShowBuilder.php
=> Use describe association

docs/reference/filter_field_definition.rst, src/Filter/BooleanFilter.php, tests/Filter/BooleanFilterTest.php
Closes #1436
```markdown
- `treat_null_as` option to BooleanFilter
```
=> Add `treat_null_as` option to BooleanFilter

src/FieldDescription/FieldDescriptionFactory.php
=> Remove useless assert

composer.json, src/Model/AuditReader.php
```markdown
- `AuditReader` compatibility with sonata-admin@4.0.0-rc.2
```
=> Use Revision class
